Issue#110 add telecom conversion
LinuxForHealth/hl7v2-fhir-converter pull request #121
Opened 2021-07-08 18:49 UTC by cragun47

This adds Telecom conversion and associated unit tests.

See Issue for description of conversion.

2021-07-08 21:09 UTC, LisaWellman requested changes
A few comments, mainly want to address extension

2021-07-08 21:09 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtilsTest.java
> +    assertThat(Hl7RelatedGeneralUtils.getFormattedTelecomNumberValue("111","","333","4444444","x555","112")).isEqualTo("(333) 444 4444 x555");
Suggest that we add some tests:
- extension not included
- country code not included
- area code not included

I am not sure how international numbers would come in, maybe they would be unformatted - we can add more later when we see real examples.

2021-07-08 21:09 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7TelecomFHIRConversionTest.java
> +    assertThat(contact.getUse()).hasToString("HOME");
The value of both use and system should be lower case.  I am not sure if these methods are checking case, but we should lowercase to be most accurate even if they do not.

2021-07-08 21:09 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7TelecomFHIRConversionTest.java
> +    assertThat(contact.getValue()).hasToString("(555) 111 1414 x889");
as mentioned elsewhere, should be `ext 889`

2021-07-08 21:09 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7TelecomFHIRConversionTest.java
> +    + "PID|1||12345678^^^^MR|ALTID|Moose^Mickey^J^III^^^||20060504|M|||||^PRN^PH^^22^555^1111313^^^^^^^^^^^2~^PRN^CP^^22^555^2221313^^^^^^^^^^^1|^PRN^PH^^^555^1111414^x889||||||||||||||||\n"
As mentnioned previously, I don't think x889 is a valid extension as it is numeric

2021-07-09 03:16 UTC, cragun47 commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +        if (xtn7Local != null && xtn7Local.length() > 0) {
Agree.  Will do.

2021-07-09 03:19 UTC, cragun47 commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +            // If an exrention exists, append a space and the extension
OK

2021-07-09 10:47 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7TelecomFHIRConversionTest.java
> +    assertThat(contact.getUse()).hasToString("HOME");
The values from the .toString are coming back caps:

>contact.getUse().toString()
"HOME"
contact.getUse()
ContactPoint$ContactPointUse@166 "HOME"

I think a better way is to use the ENUM constants of the class.  I have changed the tests similar to this:

`assertThat(contact.getUse()).isEqualTo(ContactPoint.ContactPointUse.HOME);`

2021-07-09 10:49 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7TelecomFHIRConversionTest.java
> +    assertThat(contact.getValue()).hasToString("(555) 111 1414 x889");
To match the standard you cite, I have changed it numeric content with ` ext. ` as prefix, including surrounding spaces.

2021-07-09 11:57 UTC, cragun47 commented on src/main/resources/hl7/datatype/Telecom.yml
> +     valueOf: $use
Use is passed in from the Patient.yml.  Remember there are two phone sections, so they will each have an initial use:
```
telecom_1:
    valueOf: datatype/Telecom
    generateList: true
    expressionType: resource
    specs: PID.14
    constants: 
       use: "work"

         
telecom_2:
    valueOf: datatype/Telecom
    generateList: true
    expressionType: resource
    specs: PID.13
    constants: 
       use: "home"
```

2021-07-09 11:57 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtilsTest.java
> +    assertThat(Hl7RelatedGeneralUtils.getFormattedTelecomNumberValue("111","22","333","4444444","x555","112")).contains("x555");
Done

2021-07-09 11:57 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtilsTest.java
> +    assertThat(Hl7RelatedGeneralUtils.getFormattedTelecomNumberValue("111","22","333","","x555","")).isEqualTo("111");
Fixed

2021-07-09 11:58 UTC, cragun47 commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +                returnValue = returnValue + " " + xtn8Extension;
Changed to " ext. " to match the detail in the standard.

2021-07-09 11:58 UTC, cragun47 commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +            // If an exrention exists, append a space and the extension
Fixed

2021-07-09 11:58 UTC, cragun47 commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +        if (xtn7Local != null && xtn7Local.length() > 0) {
Fixed.  Added new logic and refactored to appease the linter.

2021-07-09 11:59 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtilsTest.java
> +    assertThat(Hl7RelatedGeneralUtils.getFormattedTelecomNumberValue("111","","333","4444444","x555","112")).isEqualTo("(333) 444 4444 x555");
Added additional tests as suggested.

2021-07-09 11:59 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7TelecomFHIRConversionTest.java
> +    + "PID|1||12345678^^^^MR|ALTID|Moose^Mickey^J^III^^^||20060504|M|||||^PRN^PH^^22^555^1111313^^^^^^^^^^^2~^PRN^CP^^22^555^2221313^^^^^^^^^^^1|^PRN^PH^^^555^1111414^x889||||||||||||||||\n"
Fixed.

2021-07-09 12:00 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtilsTest.java
> +        // Country, Area, and Extension are used if there is a Local number, and XTN1 and XTN12 are ignored
Fixed.

2021-07-09 13:19 UTC, LisaWellman approved these changes

2021-07-09 13:19 UTC, merged