Message events updates for PID, PD1, AL1
LinuxForHealth/hl7v2-fhir-converter pull request #125
Opened 2021-07-12 20:15 UTC by klwhaley

Fixes Issue #123

2021-07-13 15:03 UTC, cragun47 requested changes
Recommend using common utility to create patient in test.

2021-07-13 15:03 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/message/Hl7MessageTest.java
> +    HL7ToFHIRConverter ftv = new HL7ToFHIRConverter();
I built a utility to do what you do in lines 85-98, because it is used done so often in so many place.  Recommend you use it.   It is in segments/util/PatientUtils.java.   An example of using it is in Hl7AddressFHIRConversionTest.  

If you want  to commit this, and have me make the change late, I'm willing to do that.

2021-07-13 21:33 UTC, LisaWellman commented on src/main/resources/hl7/message/ORU_R01.yml
> -              - EVN
Not sure about this one - I am not sure when we need to specify "additionalSegments"?
EVN is listed under MessageHeader for ADT-A01.
General comment as this was also removed from MessageHeader in PPR-PC1 and VXU_V04

2021-07-14 19:26 UTC, klwhaley commented on src/main/resources/hl7/message/PPR_PC1.yml
> -             - .EVN
Discussed, EVN is not supported for PPR_PC1.  No change made.

2021-07-14 19:26 UTC, klwhaley commented on src/main/resources/hl7/message/ORU_R01.yml
> -              - EVN
Discussed, EVN is not supported for ORU_R01.  No change made.

2021-07-15 14:31 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/message/Hl7MessageTest.java
> +  public void test_patient_additional_demographics() throws IOException {
fixed

2021-07-15 14:52 UTC, klwhaley commented on README.md
> +* RXC - Pharmacy/Treatment Component Order
fixed

2021-07-15 14:53 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/message/Hl7MessageTest.java
> +    HL7ToFHIRConverter ftv = new HL7ToFHIRConverter();
My test actually creates more than just a patient...it creates a practitioner from the patient PID as well. So I don't believe your function will work at this time.

2021-07-15 15:03 UTC, cragun47 approved these changes
No immediate concerns.  In the future, maybe we want to consolidate the helper functions to a utility class.

2021-07-15 15:08 UTC, merged