WIP: ADD logic for conditions  and add a few identifiers
LinuxForHealth/hl7v2-fhir-converter pull request #151
Opened 2021-07-26 18:20 UTC by jgrant22

Opening for discussion. I think so far so good. I have a general function that can be used for a lot of these cases. the cases that can't be resolved with this function (with the exception of one or two) are pretty simple and can be handled with the or symbol within the yml.

2021-07-26 19:29 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7AllergyFHIRConversionTest.java
I was using this test case just so I could see the changes in the bundle I meant to fix this. next commit will have its own test

2021-07-26 19:29 UTC, jgrant22 commented on src/main/resources/hl7/resource/Condition.yml
> +    sys: "urn:id:extID"
identifier 1 and 2 and the most common methods within the [primary identifiers document](https://ibm.ent.box.com/notes/827286128187)

2021-07-26 19:29 UTC, jgrant22 commented on src/main/resources/hl7/datatype/Identifier.yml
> +     valueOf: $value
changing this back and adding value as a valueOf option

2021-07-26 19:29 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +    }
as I look at this here... this would break the moment there's a 4th values somewhere in the field I should probably change this to ">2" and then check if the values are the same before joining them

2021-07-26 20:27 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7AllergyFHIRConversionTest.java
3.3 is the name of the coding system, so for example "LN" would be for LOINC.

2021-07-26 21:15 UTC, LisaWellman commented on src/main/resources/hl7/resource/AllergyIntolerance.yml
> +    value: AL1.3, GeneralUtils.concatenateWithHyphen(value)
I see now you are passing in the entire CXE element, and this pattern is used for several resources.  This is not a general string utility, so I think we should use a name such as "buildIdentifierFromCXE" that makes it clearer.

2021-07-26 21:15 UTC, LisaWellman commented on src/main/resources/hl7/resource/Condition.yml
> +  specs: PV1.19 | PID.18 | MSH.10
This looks good for the value, but will need to get the correct type as well.

2021-07-26 21:15 UTC, LisaWellman commented on src/main/resources/hl7/resource/Condition.yml
> +    system: SYSTEM_URL, $sys
Can you put the actual string right here?  I have not tried it, maybe it does not work.

2021-07-26 21:15 UTC, LisaWellman commented on src/main/resources/hl7/resource/Condition.yml
> +identifier_2:
Does this actually generate 2 identifiers (array of 2) or does it stop when one fires?

2021-07-26 21:17 UTC, jgrant22 commented on src/main/resources/hl7/resource/AllergyIntolerance.yml
> +    value: AL1.3, GeneralUtils.concatenateWithHyphen(value)
noted thanks!

2021-07-26 21:18 UTC, jgrant22 commented on src/main/resources/hl7/resource/Condition.yml
> +    system: SYSTEM_URL, $sys
Yea I tried that first and couldn't get it to work for some reason

2021-07-26 21:20 UTC, jgrant22 commented on src/main/resources/hl7/resource/Condition.yml
> +identifier_2:
I think if there is no condition it fires both? I haven't tested this one yet to check though. I was curious on whats expected here? the document just had both but should only one be firing? if so is there a specific case where one should be firing?

2021-07-26 22:39 UTC, LisaWellman commented on src/main/resources/hl7/resource/Condition.yml
> +identifier_2:
they should both be firing, so we should have 2 identifiers generated

2021-07-27 12:54 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7AllergyFHIRConversionTest.java
thanks  for this!

2021-07-29 20:46 UTC, jgrant22 commented on src/main/resources/hl7/resource/Condition.yml
> +identifier_2:
added condition

2021-07-29 20:47 UTC, jgrant22 commented on src/main/resources/hl7/resource/Immunization.yml
>     constants:
This way worked a little better for me.

2021-07-29 20:48 UTC, jgrant22 commented on src/main/resources/hl7/resource/Observation.yml
> +#    fillpla: STRING, OBR.2 | ORC.3 | OBR.3 | ORC.2 | MSH.7
I am kind of lost this one can we set some time and discuss

2021-08-03 19:15 UTC, cragun47 approved these changes
Minor comments.  Otherwise approved.  Good work.

2021-08-03 19:15 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/ConditionUtils.java
> +    System.out.println(json);
Probably remove or comment out the println OR change to LOGGER, if the information is important.   Because this is test, let the the user uncomment if they need to see the output.

2021-08-03 19:15 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/DiagnosticReportUtils.java
> +    System.out.println(json);
Probably remove or comment out the println OR change to LOGGER, if the information is important.   Because this is test, let the the user uncomment if they need to see the output.

2021-08-03 19:15 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/ObservationUtils.java
> +    System.out.println(json);
Probably remove or comment out the println OR change to LOGGER, if the information is important.   Because this is test, let the the user uncomment if they need to see the output.

2021-08-03 21:01 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/ObservationUtils.java
> +    System.out.println(json);
noted, okay thanks! I will make that change

2021-08-03 23:46 UTC, LisaWellman reviewed
A lot of great work here.  

I have several questions on the requirements (Elena's doc, and did we meet what she wanted).  I would like to add some examples of what we are generating (in green or some new color) to that doc and have her review.  We also need her to answer the green questions in there.  Please add the examples and then schedule a mtg with her (please invite me as well).

Missing several unit tests, or checks in existing tests.  This is must fix to ensure the code is working correctly.

2021-08-03 23:46 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +
Add tests:
- With OBR-3 for filler
- With ORC-3 for filler
- With OBR-2 for placer
- With ORC-2 for placer

2021-08-03 23:46 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +                    "PV2|||Hold for Observation||Wedding Ring|X-5546||20170822051700|20170824051700|2 days|2 days|\n" +
Remove PV2 segment, not needed.  It is not valid without PV1, if it fails may need to add PV1

2021-08-03 23:46 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +                    "NTE|1||Original Report Text Filename %%filename%%";
Remove NTE segment, not needed for this test

2021-08-03 23:46 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +                    "OBX|1|TX|||--------------------------------------------------Impression: 1. Markedly intense metabolic activity corresponding with the area of nodular enhancement in the left ora
Simplify this message - cut out almost all the text in OBX-5

2021-08-03 23:46 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +
check number of identifiers returned

2021-08-03 23:46 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +
check number of identifiers returned

2021-08-03 23:46 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +
Add check that there are 3 identifiers

2021-08-03 23:46 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +    assertThat(system).isNull();
I added a note to the doc, wondering if this should have a codeableconcept type (doc does not say it should, but want to verify).  It seems like we need a system or a type.

2021-08-03 23:46 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +    assertThat(identifier2System).isNull();
I added a note to the doc, wondering if this should have a codeableconcept type (doc does not say it should, but want to verify). It seems like we need a system or a type.

2021-08-03 23:46 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +    assertThat(identifier3Value).isEqualTo("20170825010500"); //the MSH fix will require this to change. 20170825010500 is not MSH.7
What is the MSH fix?  We want MSH10 which is MSGID22102712.  Change the test to check for that, and if there is a bug comment out that check and put in a comment with a TODO

2021-08-03 23:46 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +
Add test for:
- Using OBR-2 for placer id
- Using OBR-3 for filler id

Note that MSH-10 is a required field, so we do not need a test without MSH-10.  You could add a comment at the top of the method stating this.

2021-08-03 23:46 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +  }
Need to add tests for 
- Encounter
- Medication administration
- Medication request
- Immunization
- ServiceRequest
- Procedure
- DocumentReference

2021-08-03 23:46 UTC, LisaWellman commented on src/main/resources/hl7/resource/MedicationStatement.yml
> +#
I added a comment to the doc -- I don't think we will ever create a Medication Statement from the converter.  Need to verify.  If we do end up leaving this will need to add unit tests.

2021-08-04 21:38 UTC, LisaWellman commented on TEMPLATING.md
> +* In order to  do this we need to pass the two fields as variables into a custom Identifier type that will  join the two fields together
also on both sides of "where"  `  where  `

2021-08-04 21:38 UTC, LisaWellman commented on TEMPLATING.md
> +* In order to  do this we need to pass the two fields as variables into a custom Identifier type that will  join the two fields together
and in `from  different`

2021-08-06 16:45 UTC, LisaWellman requested changes

2021-08-06 16:45 UTC, LisaWellman commented on src/main/resources/config.properties
> +supported.hl7.messages=ADT_A01, ORU_R01, PPR_PC1, VXU_V04, RDE_O11, OMP_O09, RDE_O25, MDM_T01
Ugh, this is not ideal, as we are really not ready to call this 'supported', but I am sure you added this to get the unit test to work.  I think we either need to 
1. find a way to pass the supported message types on the convert call
2. comment out the unit test for now -- and add a note to the TXA card to uncomment it later.  You can still run the unit test in your local env with this enabled, but I do not want to deliver this enabled here.

2021-08-06 16:45 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/ConditionUtils.java
> +/*
Almost all of these <Resource>Utils classes are duplicated code.
Let's create a generic class named Utils (or FHIRUtils, or something -- I am poor at naming), and have a method 
`List<BundleEntryComponent> convertHl7Segment(String inputSegment)`
that includes up to line 40.
Move line 41 into getDiagnosticReportFromResource (I would rename to getDiagnosticReport), and of course change the parm type of this method to take the list as the input.

Then, my vote would be to move all all the individual methods for each resource type (getDiagnosticReportFromResource, and all the others from each class) into this same common utils class.  We could keep the individual classes per FHIR resource, but IMO having them all together it is easier to compare / copy, and since there is just the one method per resource it is not worth having separate classes.

2021-08-06 21:12 UTC, LisaWellman commented on src/main/resources/hl7/resource/DocumentReference.yml
> +      value: "attachment"
I added a task in card 374 to address this hardcoded content

2021-08-06 21:13 UTC, LisaWellman commented on TEMPLATING.md
> +* In order to  do this we need to pass the two fields as variables into a custom Identifier type that will  join the two fields together
these are all fixed in the latest commit

2021-08-06 21:29 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +    String justField2 = "MSH|^~\\&|SE050|050|PACS|050|20120912011230||ADT^A01|102|T|2.6|||AL|NE\r"
fixed in latest commit

2021-08-06 22:16 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +                    + "OBX|1|CE|64994-7^vaccine fund pgm elig cat^LN|1|V02^VFC eligible Medicaid/MedicaidManaged Care^HL70064||||||F|||20130531|||VXC40^per imm^CDCPHINVS\r"
It would be good to simplify the PV1 segment as well.  (and PID)

2021-08-06 22:16 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +             "ROL|5897|UP|AD|Dr Disney|20210322133821|20210322133822|10||Hospital|ST|19 Raymond St^Route 3^Albany^NY|1-555-222-3333|1-555-444-5555|USA\n" +
Remove ROL segment, not needed for this test.

2021-08-06 22:16 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +
Add tests for:
- OBR-44 not blank
- OBR-45 not blank

2021-08-06 22:16 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +
fixed in latest commit

2021-08-06 22:16 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +    assertThat(identifier2System).isNull();
Fixed in latest commit

2021-08-06 22:16 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +  }
Latest commit has added tests for Encounter, Immunization, ServiceRequest, Procedure,  DocumentReference

Still need tests for
- Medication administration
- Medication request

2021-08-09 02:37 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/ConditionUtils.java
> +/*
Okay thanks for this !

2021-08-09 02:41 UTC, jgrant22 commented on TEMPLATING.md
> +*  In the Indetifier_Observation we take the values and add them together in the `value  HL7Spec`
thanks

2021-08-09 02:49 UTC, jgrant22 commented on src/main/resources/hl7/message/OMP_O09.yml
> +    group: ORDER
https://hl7-definition.caristix.com/v2/HL7v2.5.1/TriggerEvents/OMP_O09 Service request was takes ORC segments and here ORDER is a folder with a few segments listed in it.... I added the group ORDER because of that.

2021-08-09 02:52 UTC, jgrant22 commented on src/main/resources/hl7/resource/Condition.yml
> +identifier_3:
thanks I think the original way I was doing this method needed a null check but datatype/identifier requires a value so I can get rid of it this null check now.

2021-08-09 02:53 UTC, jgrant22 commented on src/main/resources/hl7/resource/AllergyIntolerance.yml
> +  valueOf: datatype/Identifier
answer in DG1

2021-08-09 03:17 UTC, jgrant22 commented on src/main/resources/config.properties
> +supported.hl7.messages=ADT_A01, ORU_R01, PPR_PC1, VXU_V04, RDE_O11, OMP_O09, RDE_O25, MDM_T01
resolved this and switched to MDM_T02

2021-08-09 03:17 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/data/SimpleDataValueResolver.java
> +    public static final ValueExtractor<Object, String> BUILD_FROM_CWE = (Object value) -> {
thanks

2021-08-09 03:20 UTC, jgrant22 commented on src/main/resources/hl7/datatype/Identifier_Observation.yml
> +system:
nope meant to delete it

2021-08-09 03:25 UTC, jgrant22 commented on src/main/resources/hl7/datatype/Identifier_Observation.yml
> +system:
I. take that back I thought about deleting it but I do need it

2021-08-09 03:29 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +             "ROL|5897|UP|AD|Dr Disney|20210322133821|20210322133822|10||Hospital|ST|19 Raymond St^Route 3^Albany^NY|1-555-222-3333|1-555-444-5555|USA\n" +
It does not run without ROL

2021-08-09 12:27 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +             "ROL|5897|UP|AD|Dr Disney|20210322133821|20210322133822|10||Hospital|ST|19 Raymond St^Route 3^Albany^NY|1-555-222-3333|1-555-444-5555|USA\n" +
Hmm, I wonder why not.  You do not need to resolve in this PR, though it would be nice to look into sometime.

2021-08-09 12:44 UTC, LisaWellman commented on src/main/resources/hl7/message/OMP_O09.yml
> +    group: ORDER
I don't see anything about "group" in the templating guide.  Am I missing where it is documented, or can you add something?

2021-08-09 12:50 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +             "ROL|5897|UP|AD|Dr Disney|20210322133821|20210322133822|10||Hospital|ST|19 Raymond St^Route 3^Albany^NY|1-555-222-3333|1-555-444-5555|USA\n" +
I am not exactly sure why but I think it has something to do with how I set the message up possible ROL is the main segment and PR1 as an additional segment. I only did that because having PR1 as the main was not validating.

2021-08-09 13:08 UTC, LisaWellman commented on src/main/resources/hl7/resource/DocumentReference.yml
> +      valueIn: ORC.3.1 | OBR.3.1
Jared, I think we need to add (or maybe change this to) TXA15.1, see https://ibm-watsonhealth.slack.com/archives/C01RXJ8Q2ET/p1628446028029800
I think this will be evident when you get a TXA testcase.

2021-08-09 13:08 UTC, LisaWellman commented on src/main/resources/hl7/resource/DocumentReference.yml
> +      valueIn: ORC.2.1 | OBR.2.1
Jared, I think we need to add (or maybe change this to) TXA14.1, see https://ibm-watsonhealth.slack.com/archives/C01RXJ8Q2ET/p1628446028029800
I think this will be evident when you get a TXA testcase.

2021-08-09 20:17 UTC, jgrant22 commented on src/main/resources/hl7/resource/DocumentReference.yml
> +      valueIn: ORC.2.1 | OBR.2.1
I added it to the front for now

2021-08-09 20:19 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +  }
done

2021-08-09 23:18 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +    Identifier identifier2 = medAdmin.getIdentifier().get(1);
There does not seem to be an RXO segment in this message, so this should not be generated.  We should add a test with an RXO, but this is actually a good test since it seems to have exposed a problem.

2021-08-09 23:54 UTC, LisaWellman commented on src/main/resources/hl7/resource/DocumentReference.yml
> +# (C) Copyright IBM Corp. 2020
fixed in latest commits

2021-08-09 23:55 UTC, LisaWellman commented on src/main/resources/hl7/resource/Observation.yml
> +identifier_1:
A comment has been added in the most recent commits

2021-08-09 23:56 UTC, LisaWellman commented on src/main/resources/hl7/resource/Observation.yml
> +    fillpla: STRING, OBR.2.1 | ORC.3.1 | OBR.3.1 | ORC.2.1 | MSH.7
Order changed in latest comits

2021-08-10 00:07 UTC, LisaWellman approved these changes
I reviewed the new code and have a couple of comments.  There ae a few comments still not marked resolved from earlier reviews, but I think most have been addressed.
Approving, I think we are at a place we can merge after resolving the new comments,

2021-08-10 12:18 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +    Identifier identifier2 = medAdmin.getIdentifier().get(1);
this kind of confused me... request seemed like it used RXO but I didn't see any RXO in the fhir mappings doc for admin. Just RXA and RXR https://www.hl7.org/fhir/medicationadministration-mappings.html#v2

it generated because I have RXA listed as the correct segment when I tried RXO I was getting errors

2021-08-10 12:19 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/getResourceUtils.java
> +public class getResourceUtils {
will do

2021-08-10 12:19 UTC, jgrant22 commented on src/main/resources/hl7/resource/DocumentReference.yml
> +      valueIn: TXA.14.1 | ORC.2.1 | OBR.2.1
okay noted

2021-08-10 12:19 UTC, jgrant22 commented on src/main/resources/hl7/resource/DocumentReference.yml
> +      valueIn: ORC.2.1 | OBR.2.1
thanks

2021-08-10 12:22 UTC, jgrant22 commented on src/main/resources/hl7/message/OMP_O09.yml
> +    group: ORDER
It may not be documented I remembered this method from the hackathon I can add to the docs

2021-08-10 12:22 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +  }
added

2021-08-10 19:59 UTC, merged