add logic to get message type
LinuxForHealth/hl7v2-fhir-converter pull request #179
Opened 2021-08-23 21:48 UTC by jgrant22

2021-08-23 21:59 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/parsing/HL7DataExtractor.java
> +      e.printStackTrace();
wasn't sure what this meant?  the TODO comment

2021-08-23 22:13 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/FHIRConverterTest.java
> +//  }
I was using this test just to debug should I add to it and leave it commented out?

2021-08-23 23:31 UTC, LisaWellman requested changes

2021-08-23 23:31 UTC, LisaWellman commented on src/main/java/io/github/linuxforhealth/hl7/parsing/HL7DataExtractor.java
> +      e.printStackTrace();
It is a default chunk of code generated by the IDE -- need to do something appropriate in the catch block

2021-08-23 23:31 UTC, LisaWellman commented on src/main/java/io/github/linuxforhealth/hl7/parsing/HL7DataExtractor.java
> +      String theActualMessageType = msh.getMessageType().getMsg1_MessageCode().getValue() + "_" + msh.getMessageType().getMsg2_TriggerEvent().getValue();
This was Elena's hack-ish attempt to get the right value.  She was hoping there was a smarter way to get the right value.

2021-08-23 23:31 UTC, LisaWellman commented on src/main/java/io/github/linuxforhealth/hl7/parsing/HL7DataExtractor.java
> +      System.out.println(message.getName());
Remove println

2021-08-23 23:31 UTC, LisaWellman commented on src/main/java/io/github/linuxforhealth/hl7/parsing/HL7DataExtractor.java
> +    try {
Please refactor the code so it is not duplicated.  This method should be able to just call the other:
`return getMessageType(message)`

2021-08-23 23:31 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/FHIRConverterTest.java
> +//  }
Change the test so that it checks the message type retuned, and then uncomment.

2021-08-24 18:04 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/FHIRConverterTest.java
> +//  }
gotcha thanks

2021-08-24 18:07 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/parsing/HL7DataExtractor.java
> +    try {
thanks, done

2021-08-31 19:19 UTC, evbaron approved these changes
Changes look good. 
Made sure both static and instance method changed to using MSH Event Type/Trigger.
Unit test present.

2021-08-31 22:28 UTC, merged