Signed-off-by: jared.grant@ibm.com <jared.grant@ibm.com>
LinuxForHealth/hl7v2-fhir-converter pull request #200
Opened 2021-09-02 23:06 UTC by jgrant22

add filler and order systems to Identifiers and change procedure Identifiers

2021-09-07 14:51 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> -        // Test: ExtID from MSH-7, filler and placer from ORC, visit number from MSH-7
I think we should have a test with PR1, but no PR1.19, so we have to fall back to MSH-7 for the identifier.

2021-09-07 14:53 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +//                  "TXA|1||B45678|||||||||||PON001^IE|k|\n" +
total nit, but did we add the 'k' on purpose? i don't think i see us use it in tests?

2021-09-07 14:55 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +//                  "TXA|1||B45678|||||||||||PON001^IE|k|\n" +
OH i see, i think you are using it be sure you are getting TXA.14 and not TXA.15

2021-09-07 15:12 UTC, klwhaley requested changes
Please add the requested test, and fix the 3 failing tests, then I'll re-review! THanks!

2021-09-07 15:33 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> -        // Test: ExtID from MSH-7, filler and placer from ORC, visit number from MSH-7
Ahh thanks !

2021-09-07 15:47 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7IdentifierFHIRConversionTest.java
> +//                  "TXA|1||B45678|||||||||||PON001^IE|k|\n" +
I honestly don't recall why I didn't just leave this blank

2021-09-07 15:49 UTC, klwhaley commented on src/main/resources/hl7/resource/Procedure.yml
> +      systemCX: PR1.19.2
Missed this in first review, Lisa and I were discussing.  Please update back to urn:id :extID
19.2 is not a system, it has to do with the number of char/digits of the code.

So leave value PR1.19.1 | MSH.7
But change system back how you had it.

2021-09-07 16:33 UTC, jgrant22 commented on src/main/resources/hl7/resource/Procedure.yml
> +      systemCX: PR1.19.2
thanks, fixed

2021-09-08 14:24 UTC, klwhaley approved these changes
Thank you for all the updates! Looks good, Please merge!

2021-09-08 14:25 UTC, merged