Added logic to properly map MedicationRequest status
LinuxForHealth/hl7v2-fhir-converter pull request #225
Opened 2021-09-14 20:51 UTC by evbaron

MedicationRequest to use ORC.1 to determine status of MedicationRequest.

2021-09-15 13:45 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/message/Hl7RDEMessageTest.java
> +  public void test_RDEO11_medrequest_present() throws IOException {
Same comments here about simplifying the test messages

2021-09-15 13:45 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/MedicationFHIRConverterTest.java
>      @Test
If these are covered in the MedicationRequest test now, I think we can remove rather than disable.

2021-09-15 13:45 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +    System.out.println(json);
Change all println's to a logging stmt

2021-09-15 14:32 UTC, LisaWellman approved these changes
Approving with some cleanup comments, but one main comment about the subject reference removal.

2021-09-15 14:36 UTC, LisaWellman requested changes
The subject reference should be addressed, both in the yml and a check added in unit test

2021-09-16 19:33 UTC, LisaWellman commented on src/main/resources/hl7/resource/MedicationRequest.yml
> -subject:
Ah, I see, this just got moved up

2021-09-16 19:34 UTC, LisaWellman approved these changes

2021-09-16 20:08 UTC, merged

2021-09-17 11:58 UTC, evbaron commented on src/test/java/io/github/linuxforhealth/hl7/message/Hl7OMPMessageTest.java
> +		        + "PID|1||0a3be81e-144b-4885-9b4e-c5cd33c8f038^^^MRN||Patient^Load^Generator||19690720|M|Patient^Alias^Generator|C|9999^^CITY^STATE^ZIP^CAN|COUNTY|(866)845-0900||ENGLISH^ENGLISH|Married|Bap
Simplified PID and removed extra segments.

2021-09-17 11:58 UTC, evbaron commented on src/test/java/io/github/linuxforhealth/hl7/message/Hl7RDEMessageTest.java
> +  public void test_RDEO11_medrequest_present() throws IOException {
Simplified PID and removed extra segments.

2021-09-17 11:58 UTC, evbaron commented on src/test/java/io/github/linuxforhealth/MedicationFHIRConverterTest.java
>      @Test
Removed Medication tests.

2021-09-17 11:59 UTC, evbaron commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +    System.out.println(json);
Removed System.out.println commands (they were left there by accident from testing)

2021-09-17 11:59 UTC, evbaron commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +    		+ "PID|||1234^^^^MR||DOE^JANE^|||F||||||||||||||||||||||\n"
there are a few statuses that are being tested: Active, Stopped, Canceled and also it is testing handling of Unknown status. I have provided a comment for each test.