the rest of 345
LinuxForHealth/hl7v2-fhir-converter pull request #230
Opened 2021-09-16 22:43 UTC by jgrant22

PV1-2 - needed because class is required field
 PV2-3 -to do (reasonCode)
 Encounter.length.units
 PV1.4 - use mapping "assuming single character"

Signed-off-by: jared.grant@ibm.com <jared.grant@ibm.com>

2021-09-20 18:27 UTC, klwhaley commented on src/main/resources/hl7/resource/Encounter.yml
> +    specs: PV1.2
required: true should still be here...it is a required field?

2021-09-20 18:34 UTC, klwhaley commented on src/main/resources/hl7/datatype/Duration.yml
> +   value:  "Days"
pass in from higher level, if min or days?

2021-09-20 18:34 UTC, klwhaley commented on src/main/resources/hl7/datatype/Duration.yml
> +    valueOf: 'GeneralUtils.diffDateDay(var1,var2)'
want to suppot both days/min see comments in encounter yml

2021-09-20 18:36 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7EncounterFHIRConversionTest.java
> +              + "PV2|SAN BRUNO|AC4567|vomits|less equipped|purse|SAN MATEO|HO|20171014154626|20171018154634|4|3|DIAHHOREA|RSA456|20161013154626|Y|D|20191026001640|O|Y|1|F|Y|KAISER|AI|2|20161013154626
don't need PV2 for this test, remove to simplify test

2021-09-20 18:36 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7EncounterFHIRConversionTest.java
> +              + "PV2|SAN BRUNO|AC4567|vomits|less equipped|purse|SAN MATEO|HO|20171014154626|20171018154634|4|3|DIAHHOREA|RSA456|20161013154626|Y|D|20191026001640|O|Y|1|F|Y|KAISER|AI|2|20161013154626
don't need PV2 for this test, remove to simplify test

2021-09-20 18:38 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7EncounterFHIRConversionTest.java
> +
can you add another test for when there is PV2.3 and EVN.4...i think we get 2 reason codes then?

2021-09-20 18:39 UTC, klwhaley requested changes
see comments in review!

2021-09-20 18:42 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7EncounterFHIRConversionTest.java
General comment...are we missing tests on length? would liek to see tests for both minutes and days scenario.  thank you

2021-09-20 22:55 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7EncounterFHIRConversionTest.java
> +
for some reason with reason code I cant get more than one to show. It keeps overriding the first one when both fields are available

2021-09-20 22:55 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7EncounterFHIRConversionTest.java
> +              + "PV2|SAN BRUNO|AC4567|vomits|less equipped|purse|SAN MATEO|HO|20171014154626|20171018154634|4|3|DIAHHOREA|RSA456|20161013154626|Y|D|20191026001640|O|Y|1|F|Y|KAISER|AI|2|20161013154626
done thanks

2021-09-20 22:55 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7EncounterFHIRConversionTest.java
> +              + "PV2|SAN BRUNO|AC4567|vomits|less equipped|purse|SAN MATEO|HO|20171014154626|20171018154634|4|3|DIAHHOREA|RSA456|20161013154626|Y|D|20191026001640|O|Y|1|F|Y|KAISER|AI|2|20161013154626
done thanks

2021-09-20 23:01 UTC, jgrant22 commented on src/main/resources/hl7/datatype/Duration.yml
> +    valueOf: 'GeneralUtils.diffDateDay(var1,var2)'
done

2021-09-20 23:01 UTC, jgrant22 commented on src/main/resources/hl7/datatype/Duration.yml
> +   value:  "Days"
done

2021-09-21 07:27 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7EncounterFHIRConversionTest.java
added

2021-09-21 15:33 UTC, LisaWellman commented on src/main/java/io/github/linuxforhealth/hl7/data/SimpleDataValueResolver.java
> +            // Make a message in the display.
Not sure what this second comment line means.  I would just say we are defaulting to unknown.

2021-09-21 15:33 UTC, LisaWellman commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +
nit: remove blank line

2021-09-21 15:33 UTC, LisaWellman commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +
nit - remove blank line

2021-09-21 15:33 UTC, LisaWellman commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +                    return ChronoUnit.MINUTES.between(date1,date2);
This feels weird that the method is named "Day", but it returns minutes.  I would think this method would just return 0 in this case, and there would be a second method that returns minutes.  The user when then call this 'day' method first, and if 0, call the minutes method.

2021-09-21 15:33 UTC, LisaWellman commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +    public static String getTimeUnit(Object start, Object end){
If you restructure as above, this method would not be needed as the caller would know which method generated the results, and thus the time unit.

2021-09-21 15:33 UTC, LisaWellman commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +    public static String getTimeUnit(Object start, Object end){
Oh, I see you need to call this separately from the yml.

2021-09-21 15:33 UTC, LisaWellman commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +                    return ChronoUnit.MINUTES.between(date1,date2);
I see that you need a single method to call from the yml.  I would just remove the "Day" from the method name.

2021-09-21 15:33 UTC, LisaWellman commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +V3ActCode:
Shouldn't we map O to AMB?

2021-09-21 15:33 UTC, LisaWellman commented on src/main/resources/hl7/datatype/Duration.yml
> +      var3: $time3
looks like var3 not needed here

2021-09-21 15:33 UTC, LisaWellman commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +V3ActCode:
It would be useful to add a comment that this is going from PV1-2 to Encounter.class, since their table name is not very meaningful IMO

2021-09-21 15:38 UTC, LisaWellman approved these changes
Approving, main comment is about mapping O to AMB, otherwise minor cleanup comments

2021-09-21 15:50 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +                    return ChronoUnit.MINUTES.between(date1,date2);
oohh thanks! missed that

2021-09-21 15:50 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +
done

2021-09-21 16:39 UTC, jgrant22 commented on src/main/resources/hl7/datatype/Duration.yml
> +      var3: $time3
fixed

2021-09-21 16:50 UTC, merged