ADT messsage support and tests
LinuxForHealth/hl7v2-fhir-converter pull request #262
Opened 2021-10-01 13:05 UTC by lisadier

Signed-off-by: Lisa Dierkhising <lisadier@us.ibm.com>

Changes made in this PR:
- Alphabetized message types in config.properties, and added ADT_A08
- Removed unnecessary OBX from ADT_A01 yml for Encounter
- Removed unnecessary OBX from ADT_A08 yml for Encounter and moved Condition up for consistency and ease of comparing the ADT yml files.
- In HL7ADTMessageTest: cleaned up unused imports, added tests for resources on ADT_A01 and ADT_A08, added missing tests for ADT_A34 and ADT_A40 which were already in the supported message list in config.
- Turned on the DG1 Condition tests for ADT_A08

2021-10-01 17:54 UTC, klwhaley commented on src/main/resources/config.properties
> +supported.hl7.messages=ADT_A01, ADT_A08, ADT_A34, ADT_A40, OMP_O09, ORU_R01, PPR_PC1, RDE_O11, RDE_O25, VXU_V04
can you make sure to update the readme.md with the messages not listed there (and any new segments)

2021-10-01 17:56 UTC, klwhaley commented on src/main/resources/hl7/message/ADT_A01.yml
> -             - OBX
OBX should not be removed, isn't that needed for this in encounter:

reasonReference_2:
   valueOf: datatype/Reference
   condition: $Observation NOT_NULL
   evaluateLater: true
   generateList: true
   expressionType: resource
   specs: $Observation    
   
   Pretty sure I had to add it for a defect. Make sure there is an unit test for this.

2021-10-01 17:57 UTC, klwhaley commented on src/main/resources/hl7/message/ADT_A08.yml
> -             - OBX
same as above, pretty sure its required for this in encounter: 

reasonReference_2:
   valueOf: datatype/Reference
   condition: $Observation NOT_NULL
   evaluateLater: true
   generateList: true
   expressionType: resource
   specs: $Observation

2021-10-01 17:58 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/segments/HL7ConditionFHIRConversionTest.java
> +    "MSH|^~\\&|||||||ADT^A08|64322|P|2.4|123|456|ER|AL|USA|ASCII|en|2.4||||||\r",
should we update this message to 2.6?

2021-10-01 18:01 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                                + "AL1|1|DA|1605^acetaminophen^L|MO|Muscle Pain~hair loss\r" + "DG1|1||B45678|||A|\n";
could we put DG1 on its own line so its not hidden

2021-10-01 18:02 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                List<BundleEntryComponent> e = b.getEntry();
a thought on all these tests, can we see how many resources are in the bundle...too make sure there are 'extraneous' / 'unexpected' ones...ie this test would make sure only 2 exist.  then check the two are what we expect? 

lets add that too all these tests if that isn't too hard

2021-10-01 18:03 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                                + "PV1||I|INT^0001^02^ACME||||0100^ANDERSON^CARL|0148^SMITH^JAMES||SUR|||||||0148^ANDERSON^CARL|S|VisitNumber^^^ACME|A|||||||||||||||||||ACME|||||20150502090000|\n"
can we add a PD1 to this and make sure practitioner is getting created?

2021-10-01 18:05 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                                + "AL1|1|DA|1605^acetaminophen^L|MO|Muscle Pain~hair loss\n" + "DG1|1||B45678|||A|\r";
same comments as above, move DG1 to its own line

Add PD1 so we can check a practitioner is correctly there

2021-10-01 18:07 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                assertThat(json).isNotBlank();
can we add a PD1 to both a34/ a40 tests with the field filled in for practitioner

2021-10-01 18:08 UTC, klwhaley requested changes
see comments

2021-10-04 15:20 UTC, lisadier commented on src/main/resources/config.properties
> +supported.hl7.messages=ADT_A01, ADT_A08, ADT_A34, ADT_A40, OMP_O09, ORU_R01, PPR_PC1, RDE_O11, RDE_O25, VXU_V04
Updated, posted q in Slack about some segments that are already listed as supported that I didn't expect to see 'supported'.  https://ibm-watsonhealth.slack.com/archives/C01RXJ8Q2ET/p1633360475439700

2021-10-04 15:26 UTC, lisadier commented on src/main/resources/hl7/message/ADT_A01.yml
> -             - OBX
I wondered about that too.  However I found that $Observation references the Observation resource and does not need the OBX segment.  There is already a test for this in Hl7EncounterFHIRConversionTest.  There are two tests in there that are relevant: testEncounterReferencesObservationAndDiagnosis() and testEncounterReferencesObservation().  Both of these tests still pass after I removed OBX, and they are checking specifically for the Observation.

2021-10-04 15:27 UTC, lisadier commented on src/main/resources/hl7/message/ADT_A08.yml
> -             - OBX
same response as above, I checked into that before I made the commit and it looks to work well without the OBX.

2021-10-04 15:29 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/segments/HL7ConditionFHIRConversionTest.java
> +    "MSH|^~\\&|||||||ADT^A08|64322|P|2.4|123|456|ER|AL|USA|ASCII|en|2.4||||||\r",
Good idea!  I updated all of the commented out ones so that we don't make this mistake again, when the next person uncomments another one of these.

2021-10-04 15:31 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                                + "AL1|1|DA|1605^acetaminophen^L|MO|Muscle Pain~hair loss\r" + "DG1|1||B45678|||A|\n";
Yes, not sure why that one got formatted that way!  Updated.

2021-10-04 15:57 UTC, lisadier commented on src/main/resources/config.properties
> +supported.hl7.messages=ADT_A01, ADT_A08, ADT_A34, ADT_A40, OMP_O09, ORU_R01, PPR_PC1, RDE_O11, RDE_O25, VXU_V04
Resolved, the list of messages and the list of segments are updated.

2021-10-04 16:21 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                                + "PV1||I|INT^0001^02^ACME||||0100^ANDERSON^CARL|0148^SMITH^JAMES||SUR|||||||0148^ANDERSON^CARL|S|VisitNumber^^^ACME|A|||||||||||||||||||ACME|||||20150502090000|\n"
Testing the general practitioner from PD1, is covered in the Patient resource tests in Hl7PatientFHIRConversionTest.  See test_patient_additional_demographics().  My thought was that we should focus Hl7ADTMessageTest on the top-level resources rather than the secondary resources.  It is a question of how far we want to go with the tests in this file and whether we are concerned about the overlap.

2021-10-04 16:56 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                assertThat(json).isNotBlank();
Because this is going a layer deeper into sub-resource/segment support, I've added tests for this in Hl7PatientFHIRConversionTest.  (Note that I'll add this for the non-ADT messages when I get to those -- for now the other messages are commented out.)

2021-10-04 16:58 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                                + "AL1|1|DA|1605^acetaminophen^L|MO|Muscle Pain~hair loss\n" + "DG1|1||B45678|||A|\r";
I have moved DG1 to its own line, the formatter must have caught me strangely on that one.
For PD1, I've added the test in Hl7PatientFHIRConversionTest since this is going deeper into testing the content of a sub-resource for a particular segment.

2021-10-04 17:01 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                                + "PV1||I|INT^0001^02^ACME||||0100^ANDERSON^CARL|0148^SMITH^JAMES||SUR|||||||0148^ANDERSON^CARL|S|VisitNumber^^^ACME|A|||||||||||||||||||ACME|||||20150502090000|\n"
We discussed and agreed on adding additional test in the Hl7PatientFHIRConversionTest to cover multiple message types in a ParameterizedTest.  This keeps the distinction clear between the Hl7ADTMessageTest which covers the creation of top-level resources and the Resource tests which dig deeper to test the content of sub-resources.

2021-10-04 18:09 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                List<BundleEntryComponent> e = b.getEntry();
I've added this and simplified some of the messages on the disabled ones to match the intent.

2021-10-04 20:35 UTC, lisadier commented
I've reviewed the Encounter resource and found that serviceProvider needed some beefed up tests to cover the different message types.  Those updates are in the last commit, after the 'review comments' commit.

2021-10-04 22:56 UTC, lisadier commented
Also, now added tests for ADT messages and other supported message types, for sub-resources under Observation.  Note MDM messages were not included and I'll add those in a future PR.  (I've uncovered a potential problem with MDM_T02 so I'll handle that when I address MDM messages.)

2021-10-04 23:19 UTC, lisadier commented
I have confirmed that Condition has sufficient tests to cover the resources generated.

This concludes the work on this card for the ADT messages.

2021-10-05 18:14 UTC, lisadier commented
Lisa W asked for the disabled test on Encounter.type to be removed so I've included that in the last commit.  
In addition, I also added a comment regarding PPR messages in the ConditionTests to leave 'breadcrumbs' for ourselves about the decisions made.

2021-10-05 18:22 UTC, klwhaley approved these changes
Love the new test coverage!

2021-10-05 18:22 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +        @Test@Disabled
could you update to @Disabled('adt-a02 not yet supported')

2021-10-05 18:22 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +        public void test_adta03_patient_encounter_present() throws IOException {
could you update to @Disabled('adt-a03 not yet supported')

2021-10-05 18:22 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +        @Test@Disabled
could you update to @Disabled('adt-a04 not yet supported')

2021-10-05 18:22 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +        @Test@Disabled
could you update to @Disabled('adt-a28 not yet supported')

2021-10-05 18:22 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +        @Test@Disabled
could you update to @Disabled('adt-a31 not yet supported')

2021-10-05 18:22 UTC, klwhaley commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7EncounterFHIRConversionTest.java
> +        String hl7message = msh //"MSH|^~\\&|WHI_LOAD_GENERATOR|IBM_TORONTO_LAB||IBM|20210330144208|8078780|ADT^A02|MSGID_4e1c575f-6c6d-47b2-ab9f-829f20c96db2|T|2.3\n"
remove commented out msh here, since we will enable it in parameterized section above

2021-10-05 18:48 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7EncounterFHIRConversionTest.java
> +        String hl7message = msh //"MSH|^~\\&|WHI_LOAD_GENERATOR|IBM_TORONTO_LAB||IBM|20210330144208|8078780|ADT^A02|MSGID_4e1c575f-6c6d-47b2-ab9f-829f20c96db2|T|2.3\n"
Updated.

2021-10-05 18:48 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +        @Test@Disabled
Updated.

2021-10-05 18:48 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +        @Test@Disabled
Updated

2021-10-05 18:48 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +        @Test@Disabled
Updated

2021-10-05 18:48 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +        public void test_adta03_patient_encounter_present() throws IOException {
Updated

2021-10-05 18:49 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +        @Test@Disabled
Updated

2021-10-05 21:02 UTC, merged