fix doseQuantity  value add location reference (needs better mapping )
LinuxForHealth/hl7v2-fhir-converter pull request #346
Opened 2021-11-22 21:47 UTC by jgrant22

Signed-off-by: jared.grant@ibm.com <jared.grant@ibm.com>

2021-11-22 21:54 UTC, LisaWellman commented on gradle.properties
> +localDevEnv = true
This should not be delivered

2021-11-22 22:14 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +                + "RXA|0|1|20130531|20130531|48^HIB PRP-T^CVX|0.5|ML^^ISO+||00^new immunization record^NIP001|^Sticker^Nurse|^^^RI2050^ACTIVE||||33k2a|20131210|PMC^sanofi^MVX|||CP|A|20120901041038\r"
I do not think we will map 11.5, you can revert this

2021-11-22 22:14 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/ResourceUtils.java
> +        System.out.println(json);
do no deliver this

2021-11-22 22:17 UTC, LisaWellman requested changes

2021-11-22 22:17 UTC, LisaWellman commented on src/main/resources/hl7/resource/Immunization.yml
> +location:
Let's remove this and use this branch just for the doseQuantity fix.
For location I think we should map  similar to PV1-3 (where we just did .4 facility)

2021-11-22 22:17 UTC, LisaWellman commented on src/main/resources/hl7/resource/Location.yml
> +#
See above comment about facility

2021-11-22 22:49 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +                + "RXA|0|1|20130531|20130531|48^HIB PRP-T^CVX|0.5|ML^^ISO+||00^new immunization record^NIP001|^Sticker^Nurse|^^^RI2050^ACTIVE||||33k2a|20131210|PMC^sanofi^MVX|||CP|A|20120901041038\r"
done

2021-11-22 22:49 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/ResourceUtils.java
> +        System.out.println(json);
thanks

2021-11-22 22:50 UTC, jgrant22 commented on src/main/resources/hl7/resource/Immunization.yml
> +location:
removed

2021-11-22 22:50 UTC, jgrant22 commented on src/main/resources/hl7/resource/Location.yml
> +#
removed

2021-11-22 22:52 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/data/SimpleDataValueResolver.java
> +    public static final ValueExtractor<Object, String> DOSE_VALUE = (Object value) -> {
added

2021-11-22 22:52 UTC, jgrant22 commented on gradle.properties
> +localDevEnv = true
thanks

2021-11-23 13:43 UTC, LisaWellman approved these changes

2021-11-23 15:51 UTC, merged