fix status reason to show only when status comes back as "not-done"
LinuxForHealth/hl7v2-fhir-converter pull request #356
Opened 2021-12-03 21:14 UTC by jgrant22

Signed-off-by: jared.grant@ibm.com <jared.grant@ibm.com>

2021-12-07 21:04 UTC, LisaWellman requested changes
I have some comments on logic.
Still need to review tests

2021-12-07 21:27 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/data/SimpleDataValueResolver.java
> +        else return "complete";
thanks though I deleted it.

2021-12-07 21:30 UTC, jgrant22 commented on src/main/resources/hl7/resource/Immunization.yml
> +      rxa: RXA.18
done

2021-12-07 21:30 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/data/SimpleDataValueResolver.java
> +        System.out.print(commonCodingSystemV2(table, code, text, version));
done

2021-12-07 21:32 UTC, jgrant22 commented on src/main/resources/hl7/resource/Immunization.yml
> +      code: RXA.20 | ORC.5
done

2021-12-08 15:00 UTC, jgrant22 commented on src/main/resources/hl7/resource/Immunization.yml
> +      code: $co
done

2021-12-08 15:01 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +        if (rxa == null){
function fixed after convo

2021-12-08 15:01 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +        else return "not-done";
done

2021-12-08 15:01 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +    public static String getImmunizationStatus(Object rxa, Object status){
thanks done

2021-12-08 21:22 UTC, LisaWellman requested changes
Mostly minor cleanup.
Main concerns about the statusReason = PATOBJ
- the current test where this is set is should not be
- need a test where this is set because RXA.20=RE (and RXA-18 not set)
- issue in yml is likely causing the incorrect ebhavior

2021-12-08 21:22 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(immunization.getStatus().getDisplay()).isEqualTo("completed"); // ORC.5 is PA which converts to completed.
nit - it would be nice to have blank lines separating the separate field checks (eg after line 153, 154), perhaps with a comment about the field being validated.
General comment for all tests.

2021-12-08 21:22 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(immunization.hasStatusReason()).isTrue();
I think in this case there should be no statusReason -- check should be isFalse() -- since there is no RXA-18 or RXA-20.

2021-12-08 21:22 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>          hl7VUXmessageRep = "MSH|^~\\&|MYEHR2.5|RI88140101|KIDSNET_IFL|RIHEALTH|20130531||VXU^V04^VXU_V04|20130531RI881401010105|P|2.5.1|||NE|AL||||||RI543763\r"
Add comment that this tests when no RXA-18, RXA-20 or ORC-5, so status will default to completed

2021-12-08 21:22 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(immunization.getStatus().getDisplay()).isEqualTo("completed");
add comment that this is the default, since no RXA-18, RXA-20 or ORC-5

2021-12-08 21:22 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>      //  RXA-20 (status, statusReason, isSubpotent)
Remove TODO for status, statusReason
I think isSubpotent is still a TODO

2021-12-08 21:22 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(immunization.hasStatusReason()).isFalse();
Need one more test that checks statusReason is set to PATOBJ if there is no RXA-18 and RXA-20 is RE

2021-12-08 22:13 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +    public static String getImmunizationStatus(Object rxa18, Object rxa20, Object orc5) {
done

2021-12-08 23:25 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/data/Hl7RelatedGeneralUtils.java
> +            if (code != null){
done

2021-12-08 23:26 UTC, jgrant22 commented on src/main/resources/hl7/resource/Immunization.yml
> +   condition: $code NOT_NULL
We have to pass it to a var first

2021-12-08 23:27 UTC, jgrant22 commented on src/main/resources/hl7/resource/Immunization.yml
>        code: RXA.18
done

2021-12-08 23:28 UTC, jgrant22 commented on src/main/resources/hl7/resource/Immunization.yml
> +   condition: $rxa18 NULL && statCode NOT_NULL
we have to pass it to variable first

2021-12-08 23:29 UTC, jgrant22 commented on src/main/resources/hl7/resource/Immunization.yml
> +      statCode: RXA.20 | ORC.5
done

2021-12-08 23:29 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +                + "RXA|0|1|20130531|20130531|48^HIB PRP-T^CVX|0.5|ML^^ISO+||00^new immunization record^NIP001|^Sticker^Nurse|^^^RI2050||||33k2a|20131210|PMC^sanofi^MVX|00^Patient refusal^NIP002||CP|A
this comment is on line 43

2021-12-08 23:32 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(resource.hasStatusReason()).isTrue(); //if status is "not-done" we show display
thanks I think this comment is outdated

2021-12-08 23:34 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +                + "ORC|RE||197027||CP|||||^Clerk^Myron|||||||RI2050\r"
done

2021-12-08 23:34 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(resource.getStatusReason().getCodingFirstRep().getDisplay()).isEqualTo("Patient refusal"); //RXA.18
done

2021-12-08 23:35 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>          // Test should only return RXA.10, ORC.12  is empty
done

2021-12-08 23:36 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>          String hl7VUXmessageRep = "MSH|^~\\&|MYEHR2.5|RI88140101|KIDSNET_IFL|RIHEALTH|20130531||VXU^V04^VXU_V04|20130531RI881401010105|P|2.5.1|||NE|AL||||||RI543763\r"
comments on line 43

2021-12-08 23:39 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>          // Test should only return RXA.10, ORC.12  is empty
commented on line 126

2021-12-08 23:41 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(immunization.hasStatusReason()).isTrue();
fixed

2021-12-08 23:41 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>          hl7VUXmessageRep = "MSH|^~\\&|MYEHR2.5|RI88140101|KIDSNET_IFL|RIHEALTH|20130531||VXU^V04^VXU_V04|20130531RI881401010105|P|2.5.1|||NE|AL||||||RI543763\r"
added

2021-12-08 23:42 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>      //  RXA-20 (status, statusReason, isSubpotent)
done

2021-12-08 23:43 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(immunization.hasStatusReason()).isFalse();
done

2021-12-09 00:07 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +                + "RXA|0|1|20130531|20130531|48^HIB PRP-T^CVX|0.5|ML^^ISO+||00^new immunization record^NIP001|^Sticker^Nurse|^^^RI2050||||33k2a|20131210|PMC^sanofi^MVX|00^Patient refusal^NIP002||CP|A
Yes, it is good to have here as well so no one changes the message without realizing the field is there for a purpose.  The test would still work, but it would no longer be testing everything we intend to,

2021-12-09 00:27 UTC, LisaWellman approved these changes
Just asking for more comments and a couple cleanup items, but things look good!

2021-12-09 00:27 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        hl7VUXmessageRep = "MSH|^~\\&|MYEHR2.5|RI88140101|KIDSNET_IFL|RIHEALTH|20130531||VXU^V04^VXU_V04|20130531RI881401010105|P|2.5.1|||NE|AL||||||RI543763\r"
Add a comment explaining the purpose of this test

It seems to be what the previous test was before:
`Tests when no RXA-18, RXA-20 or ORC-5, so status will default to completed`

2021-12-09 00:27 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>          hl7VUXmessageRep = "MSH|^~\\&|MYEHR2.5|RI88140101|KIDSNET_IFL|RIHEALTH|20130531||VXU^V04^VXU_V04|20130531RI881401010105|P|2.5.1|||NE|AL||||||RI543763\r"
I see it was added on line 177 but it would be nice to have before the test as well to understand the purpose without looking at the checks in detail.

2021-12-09 00:27 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(immunization.hasStatusReason()).isFalse();
Add a check for isSubpotent here, or move that TODO (line 193) here

2021-12-09 00:27 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>          hl7VUXmessageRep = "MSH|^~\\&|MYEHR2.5|RI88140101|KIDSNET_IFL|RIHEALTH|20130531||VXU^V04^VXU_V04|20130531RI881401010105|P|2.5.1|||NE|AL||||||RI543763\r"
Add to comment that we are also testing:
set statusReason=PATOBJ since no RXA-18 and RXA.20=RE

2021-12-09 00:27 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>          assertThat(immunization.getStatusReason().getCodingFirstRep().getDisplay()).isEqualTo("Patient Refusal");
Add check for text="Patient Refusal"

2021-12-09 00:27 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>          // Test should only return RXA.10, ORC.12  is empty
yes, but it is nice to have a comment at the top of the test explaining the purpose of the test (how it differs from others) without looking at the details of the checks.

2021-12-09 00:27 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +                + "ORC|RE||197027||CP|||||^Clerk^Myron|||||||RI2050\r"
Not seeing a comment added, unresolving.
The purpose of adding the comment here is so that no one changes the segment to remove ORC-5 without realizing it is there for a reason.  The test would not break, but it would no longer be testing all that we intended it to.

2021-12-09 05:07 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        hl7VUXmessageRep = "MSH|^~\\&|MYEHR2.5|RI88140101|KIDSNET_IFL|RIHEALTH|20130531||VXU^V04^VXU_V04|20130531RI881401010105|P|2.5.1|||NE|AL||||||RI543763\r"
added

2021-12-09 05:07 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(immunization.hasStatusReason()).isFalse();
done

2021-12-09 05:08 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>          hl7VUXmessageRep = "MSH|^~\\&|MYEHR2.5|RI88140101|KIDSNET_IFL|RIHEALTH|20130531||VXU^V04^VXU_V04|20130531RI881401010105|P|2.5.1|||NE|AL||||||RI543763\r"
added

2021-12-09 05:08 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>          assertThat(immunization.getStatusReason().getCodingFirstRep().getDisplay()).isEqualTo("Patient Refusal");
done

2021-12-09 05:08 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>          hl7VUXmessageRep = "MSH|^~\\&|MYEHR2.5|RI88140101|KIDSNET_IFL|RIHEALTH|20130531||VXU^V04^VXU_V04|20130531RI881401010105|P|2.5.1|||NE|AL||||||RI543763\r"
done

2021-12-09 05:08 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +                + "ORC|RE||197027||CP|||||^Clerk^Myron|||||||RI2050\r"
I think this was moved but added to the top of the message

2021-12-09 05:09 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>          // Test should only return RXA.10, ORC.12  is empty
added

2021-12-09 05:09 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +                + "RXA|0|1|20130531|20130531|48^HIB PRP-T^CVX|0.5|ML^^ISO+||00^new immunization record^NIP001|^Sticker^Nurse|^^^RI2050||||33k2a|20131210|PMC^sanofi^MVX|00^Patient refusal^NIP002||CP|A
added

2021-12-09 14:09 UTC, merged