immunization reaction date and details
LinuxForHealth/hl7v2-fhir-converter pull request #365
Opened 2021-12-14 18:04 UTC by jgrant22

Immunization.reaction.detail when OBX.3 is 31044-1 (Immunization reaction) PR 361. This is a reference to an Observation that will need to be created.
 OBX-14 should be added to Immunization to set Immunization.reaction.date, unit tests with this

2021-12-15 00:40 UTC, LisaWellman requested changes

2021-12-15 00:40 UTC, LisaWellman commented on src/main/resources/hl7/secondary/Reaction.yml
> +      obx3: String, OBX.3.1
Lets name this obx31, and then the next var obx3

2021-12-15 00:40 UTC, LisaWellman commented on src/main/resources/hl7/resource/Immunization.yml
> +   condition: $obx5 NOT_NULL
I expected to see the check for OBX-3=31044-1 here.  Without that check, I think we will create a reaction in cases where it should not be,

2021-12-15 00:40 UTC, LisaWellman commented on src/main/resources/hl7/resource/Simple_Observation.yml
> +# (C) Copyright IBM Corp. 2020, 2021
Fix date

2021-12-15 00:40 UTC, LisaWellman commented on src/main/resources/hl7/resource/Simple_Observation.yml
> +---
Add a comment how this is different than the "regular" Observation so others know when it might be appropriate to use it.

2021-12-15 00:40 UTC, LisaWellman commented on src/main/resources/hl7/resource/Simple_Observation.yml
> +---
I would like to know what the problems were that required a new yml (I've got some ideas...)

2021-12-15 00:40 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        // Immunization.Reaction Date (OBX.5) and Detail (OBX.5 if OBX 3 is 31044-1)
Fix comment - date is from OBX-14, not OBX-5

2021-12-15 00:40 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(obs.getId()).isEqualTo(reactionDetail);
This doesn't look right.  The observation is the reaction.
I could expect the code to be that it seems is in the category.
I would not expect what is in the code (31044-1, Reaction) to be in the Observation at all.

2021-12-15 00:40 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(immunization.getReactionFirstRep().getDetail().hasReference()).isFalse();
This is a good check, glad that you are adding where we do not want something to appear.
This is where I would think that we would not have a Immunization.reaction at all though; it looks like we do get one created.

2021-12-15 19:48 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(obs.getId()).isEqualTo(reactionDetail);
ahh okay I thought we wanted that to be obx3. fixed! I removed category as well

2021-12-15 19:48 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(immunization.getReactionFirstRep().getDetail().hasReference()).isFalse();
fixed!

2021-12-15 21:47 UTC, LisaWellman requested changes
Much better, some cleanup and a couple issues remaining

2021-12-15 21:47 UTC, LisaWellman commented on src/main/resources/hl7/secondary/ImmunizationReaction.yml
> +   vars:
I don't think we need to pass OBX.3 on to the Observation.

I expect that we need to pass OBX.5 on, which should become Observation.code

2021-12-15 21:47 UTC, LisaWellman commented on src/main/resources/hl7/secondary/ImmunizationReaction.yml
> +
nit - remove extra newline

2021-12-15 21:47 UTC, LisaWellman commented on src/main/resources/hl7/secondary/ImmunizationReaction.yml
> +      statusCode: 'final'
It looks like status defaults to unknown today, I think I would just stay with that  -- please remind me if I forgot we talked about 'final'!

2021-12-15 21:47 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/ResourceUtils.java
> +        System.out.print(json);
remove println

2021-12-15 21:47 UTC, LisaWellman commented on src/main/resources/hl7/resource/Observation.yml
> +   valueOf: OBX.11 | $statusCode
Given my other comment, we can remove this and just let the default 'unknown' fire.

2021-12-15 21:47 UTC, LisaWellman commented on src/main/resources/hl7/resource/Immunization.yml
> +      obx5: OBX.5
It looks like this obx5 var is not used

2021-12-15 21:47 UTC, LisaWellman commented on src/main/resources/hl7/resource/Observation.yml
> +   -  condition: $obx5 NOT_NULL
Let's add a comment that this is used when creating an Observation from a Immunization reaction.

2021-12-15 21:47 UTC, LisaWellman commented on src/main/resources/hl7/resource/Observation.yml
>        expressionType: resource
I am a little worried we might hit this condition in some other cases (we are not hitting it now because OBX-2 is CWE in the test).  I guess we can worry about that when we hit it.

2021-12-15 21:47 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/message/Hl7VXUMessageTest.java
> +        assertThat(observationResource).hasSize(1);  // TODO: Change this to 2 when card 688 is implemented, expect 2 Observations for the OBX with OBX.3 of 31044-1
Why are we not getting 2 like the comment says?  Need to resolve.

2021-12-15 21:47 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/message/Hl7VXUMessageTest.java
> +        assertThat(observationResource).hasSize(2); // TODO: Change this to 3 when card 688 is implemented, expect 2 Observations for the OBX with OBX.3 of 31044-1
Why are we not getting 3 like the comment says?  Need to resolve.

2021-12-15 21:47 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/message/Hl7VXUMessageTest.java
> +        assertThat(e.size()).isEqualTo(6);
And this should be 7 then

2021-12-15 21:47 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        String reactionDetail = resource.getReactionFirstRep().getDetail().getReference();
Move this line after line 107 where we check that we have a reference

2021-12-15 21:47 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(obs.getIdentifierFirstRep().getValue()).isEqualTo("197027-31044-1-LN");
Ooh, tough one, and good catch by putting in a check to verify the ID.

In this case, we want the ID to be
`197027-VXC9-CDCPHINVS`
meaning we use OBX-5 instead of OBX-3, because we want to use what is put in Observation.code

2021-12-15 22:07 UTC, jgrant22 commented on src/main/resources/hl7/secondary/ImmunizationReaction.yml
> +      statusCode: 'final'
I just put final to match the GT I will remove

2021-12-15 22:44 UTC, jgrant22 commented on src/main/resources/hl7/resource/Observation.yml
> +   valueOf: OBX.11 | $statusCode
done

2021-12-15 22:45 UTC, jgrant22 commented on src/main/resources/hl7/secondary/ImmunizationReaction.yml
> +   vars:
thanks got it!

2021-12-15 22:45 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/ResourceUtils.java
> +        System.out.print(json);
done

2021-12-15 22:46 UTC, jgrant22 commented on src/main/resources/hl7/secondary/ImmunizationReaction.yml
> +
done

2021-12-15 22:47 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        String reactionDetail = resource.getReactionFirstRep().getDetail().getReference();
done

2021-12-15 22:47 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(obs.getIdentifierFirstRep().getValue()).isEqualTo("197027-31044-1-LN");
fixed

2021-12-15 23:49 UTC, LisaWellman commented on src/main/java/io/github/linuxforhealth/hl7/data/SimpleDataValueResolver.java
> +       else if (value instanceof Varies){
Move the first part of this up to before line 545 and you can remove the duplicate code:

```
if (value instanceof Varies){
    Varies variesValue = ((Varies) value);
     if(variesValue.getData() instanceof CWE) {
          value = (CWE) variesValue.getData();
     }
}
```

2021-12-15 23:49 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/ResourceUtils.java
> +        System.out.print(json);
not seeing in last commit, maybe still in your workspace?

2021-12-16 00:03 UTC, LisaWellman commented on src/main/resources/hl7/resource/Observation.yml
>  identifier_1: #joins filler | placer | MSH.7 with whatever gets returned from BUILD_FROM_CWE. that magic happens in identifier_Observation
Please make the variable name more descriptive, eg useObx5

2021-12-16 00:03 UTC, LisaWellman commented on src/main/resources/hl7/secondary/ImmunizationReaction.yml
> +      id: $detailId
can you just put `true` here and avoid the constant?

2021-12-20 20:44 UTC, jgrant22 commented on src/main/resources/hl7/resource/Observation.yml
>  identifier_1: #joins filler | placer | MSH.7 with whatever gets returned from BUILD_FROM_CWE. that magic happens in identifier_Observation
went back to the original idea of SimpleObservation

2021-12-20 20:44 UTC, jgrant22 commented on src/main/resources/hl7/resource/Observation.yml
> +identifier_3:
went back to the original idea of SimpleObservation

2021-12-20 20:51 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/data/SimpleDataValueResolver.java
> +       else if (value instanceof Varies){
fixed

2021-12-20 20:52 UTC, jgrant22 commented on src/main/resources/hl7/secondary/ImmunizationReaction.yml
> +      id: $detailId
this is changed. no longer needed

2021-12-20 21:11 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/message/Hl7VXUMessageTest.java
> +        assertThat(e.size()).isEqualTo(6);
fixed

2021-12-20 21:11 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/message/Hl7VXUMessageTest.java
> +        assertThat(observationResource).hasSize(2); // TODO: Change this to 3 when card 688 is implemented, expect 2 Observations for the OBX with OBX.3 of 31044-1
fixed

2021-12-20 21:11 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/message/Hl7VXUMessageTest.java
> +        assertThat(observationResource).hasSize(1);  // TODO: Change this to 2 when card 688 is implemented, expect 2 Observations for the OBX with OBX.3 of 31044-1
fixed

2021-12-20 21:11 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/ResourceUtils.java
> +        System.out.print(json);
fixed

2021-12-20 21:35 UTC, cragun47 requested changes
Please address the questions on comments and ensure we are covering our edge cases.

2021-12-20 21:35 UTC, cragun47 commented on src/main/resources/hl7/resource/SimpleObservation.yml
> +#Observation resource
Make comment in header: `SimpleObservation`
Provide a small explanation of when you use it and how it differs from Observation. You can reference the comments on lines 29-32.

I lean toward renaming it `Observation_Simple` so it groups and sorts with `Observation.yml`

2021-12-20 21:35 UTC, cragun47 commented on src/main/resources/hl7/resource/SimpleObservation.yml
> +# The expression is nested and values are passed to the nested so that BOTH values control the 'all or nothing'
Nested in CodeableConcept?  Trying to follow this.  I only see one value, OBX.5.  OBX.5 is a _varies_ type.   So how does the underlying code "reject" the creation.

2021-12-21 00:04 UTC, jgrant22 commented on src/main/resources/hl7/resource/SimpleObservation.yml
> +# The expression is nested and values are passed to the nested so that BOTH values control the 'all or nothing'
this comment does not belong. I cleaned this up

2021-12-21 00:04 UTC, jgrant22 commented on src/main/resources/hl7/resource/SimpleObservation.yml
> +#Observation resource
this for this I added the fix

2021-12-21 00:04 UTC, cragun47 commented on src/main/resources/hl7/resource/SimpleObservation.yml
> +#Observation resource
Good. Thanks.

2021-12-21 00:09 UTC, cragun47 approved these changes
Thanks for making fixes.

2021-12-21 00:12 UTC, merged

2021-12-21 19:05 UTC, LisaWellman commented on src/main/resources/hl7/resource/Immunization.yml
> +      obx5: OBX.5
fixed in latest commits