MedicationRequest.dispenseRequest still working on dosage instruction
LinuxForHealth/hl7v2-fhir-converter pull request #377
Opened 2021-12-23 15:12 UTC by jgrant22

Map RXO-23 to MedicationRequest.dosageInstruction.maxDosePerPeriod, with RXE-19 as backup
 Map x.1 to MedicationRequest.dosageInstruction.maxDosePerPeriod.numerator.value
 Map x.2 to MedicationRequest.dosageInstruction.maxDosePerPeriod.numerator.unit, use http://unitsofmeasure.org for the system
 Set MedicationRequest.dosageInstruction.maxDosePerPeriod.denominator.value to 1
 Set MedicationRequest.dosageInstruction.maxDosePerPeriod.denominator.unit to "day", use http://unitsofmeasure.org for the system
 
 ***working on***
 Map RXO-7 to MedicationRequest.dosageInstruction.patientInstruction, with RXE-7 as backup
 If x.1 (eg RXO.7.1) exists, use x.1 + ":" + x.2 (the field is set to the code, a colon, and then text)
 if x.1 does not exist, use x.2 (the field is set to the text)
 Map RXO-5 to MedicationRequest.dosageInstruction.route, with RXE-6 as backup
 Map RXO-6.2 to MedicationRequest.dosageInstruction.text, with RXE-21.2 as backup
 If x.1 (eg RXO.6.1) exists, use x.1 + ":" + x.2 (the field is set to the code, a colon, and then text)
 if x.1 does not exist, use x.2 (the field is set to the text)

2021-12-23 16:52 UTC, cragun47 requested changes

2021-12-23 16:52 UTC, cragun47 commented on src/main/resources/hl7/secondary/DispenseRequest.yml
> +
Please add comment explaining the logic will cause values to come from RXO or RXE so they are not mixed.

2021-12-23 16:52 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +
Please break these into two tests.   SonarQube requires less that 25 asserts, and because there are two calls to parse the message, we don't need to keep them together.  You can use a numbering system or other descriptor to distinguish the test names.

2021-12-23 16:52 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +        String hl7message = "MSH|^~\\&|WHI_LOAD_GENERATOR|IBM_TORONTO_LAB|MEDORDER|IBM|20210101000000|90103687|OMP^O09|MSGID|T|2.6\n"
Please reduce messages to minimal required fields.
 MSH is `MSH|^~\\&|||||20210101000000||OMP^O09|MSGID|T|2.6`
 PID is fine
 Add comments within the message about which fields are important to the test.  Either because they are present or purposely empty.  This aids understanding and focus to important fields.
 
 You should identify important fields via comments in both the message constant and the lines that test it (which you have done.)

2021-12-23 16:52 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "RXO|00054418425^Dexamethasone 4 MG Oral Tablet^NDC^^^^^^dexamethasone (DECADRON) 4 MG TABS||||||Take 1 tablet by mouth every 6 (six) hours.||G||4|tablet^tablet|0|222^JONES^JON^E.||
Recommend breaking up the concatenated RXO line into multiple concatenated lines, in the fashion shown below for IN1, which is very long.   The level of detail can vary to match the need.

```java
        String hl7message = "MSH|^~\\&|||||20151008111200||ADT^A01^ADT_A01|MSGID000001|T|2.6|||||||||\n"
                + "EVN||20210407191342||||||\n"
                + "PID|||MR1^^^XYZ^MR||DOE^JANE^|||F||||||||||||||||||||||\n"
                + "PV1||I||||||||||||||||||||||||||||||||||||||||||\n"
                // IN1 Segment is split and concatenated for easier understanding. (| precedes numbered field.)
                // IN1.2.1, IN1.2.3 to Identifier 1
                // IN1.2.4, IN1.2.6 to Identifier 2
                + "IN1|1|Value1^^System3^Value4^^System6"
                // Minimal Organization. Required for Payor, which is required.
                // Organization deep test in testBasicInsuranceCoverageFields
                // IN1.3 to Organization Identifier 
                //    IN1.3.1 to Organization Identifier.value
                //    IN1.3.4 to Organization Identifier.system
                // IN1.4 to Organization Name
                + "|IdValue1^^^IdSystem4^^^^|Large Blue Organization|||"
                // IN1.8 to Coverage.class.value
                // IN1.9.1 to Coverage.class.name
                // IN1.12 to Coverage.period.start
                // IN1.13 to Coverage.period.end
                // IN1.14 through IN1.15 NOT REFERENCED
                + "|UA34567|Blue|||20201231145045|20211231145045||"
                // IN1.16 to RelatedPerson.name
                //    IN1.16.1 to RelatedPerson Name .family
                //    IN1.16.2 to RelatedPerson Name .given (first)
                //    IN1.16.5 to RelatedPerson Name .prefix
                // IN1.17 to RelatedPerson.relationship
                // IN1.18 to RelatedPerson.birthDate
                // IN1.19 to RelatedPerson.address (All XAD standard fields)
                // IN1.20 through IN1.35 NOT REFERENCED
                + "|DoeFake^Judy^^^Rev.|MTH|19780429|19 Rose St^^Faketown^CA^ZIP5||||||||||||||||"
                // IN1.36 to Identifier 4
                // IN1.43 to RelatedPerson.gender
                // IN1.46 to Identifier 3
                // IN1.49 to RelatedPerson.identifier
                // IN1.50 through IN1.53 NOT REFERENCED
                + "|MEMBER36|||||||F|||Value46|||J494949||||\n";
```

2021-12-23 17:52 UTC, jgrant22 commented on src/main/resources/hl7/secondary/DispenseRequest.yml
> +
added

2021-12-23 17:52 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +        String hl7message = "MSH|^~\\&|WHI_LOAD_GENERATOR|IBM_TORONTO_LAB|MEDORDER|IBM|20210101000000|90103687|OMP^O09|MSGID|T|2.6\n"
thanks, simplified the two test

2021-12-23 17:53 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "RXO|00054418425^Dexamethasone 4 MG Oral Tablet^NDC^^^^^^dexamethasone (DECADRON) 4 MG TABS||||||Take 1 tablet by mouth every 6 (six) hours.||G||4|tablet^tablet|0|222^JONES^JON^E.||
noted , split RXO and RXE

2021-12-23 17:53 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +
noted, split into two

2021-12-27 13:44 UTC, cragun47 approved these changes
Thanks for making requested updates.

2021-12-27 16:35 UTC, merged