all of dosage  instruction except dose range
LinuxForHealth/hl7v2-fhir-converter pull request #378
Opened 2021-12-30 17:16 UTC by jgrant22

all of dosageInstruction.doseAndRate
except dosageInstruction.doseAndRate.doseRange
from [705](https://github.ibm.com/WH-Imaging/Clinical-Data-Pipeline/issues/705)

2021-12-30 18:16 UTC, cragun47 requested changes
Nice work.  Please crisp up tests as requested.  IF any tests can use the same `ResourceUtils.createFHIRBundleFromHL7MessageReturnEntryList`, please combine to save parsing.  (Of course, only if they  combine well.).

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "RXE|^Q24H&0600^^20210330144208^^ROU|DUONEB3INH^3 ML PLAS CONT : IPRATROPIUM-ALBUTEROL 0.5-2.5 (3) MG/3ML IN SOLN^ADS^^^^^^ipratropium-albuterol (DUONEB) nebulizer solution 3 mL|3||
Simplify.  You're testing RXE.7.  Only RXE.2, 3, 5 are required.

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "PV1||I|^^^Toronto^^5642 Hilly Av||||||770542^Doctor^Consulting^Jr||||||||||Visit_111|||||||||||||||||||||||||20210101000000\n"
Simplify ORC and RXO to minimal fields being tested.

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +    }
Assert total resources created.

        // Verify no extraneous resources
        // Expect encounter, patient, practitioner, condition. <<??? don't know what you expect here.>>>
        assertThat(e).hasSize(4);

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +    }
// Verify no extraneous resources
        // Expect encounter, patient, practitioner, condition. <<??? don't know what you expect here.>>>
        assertThat(e).hasSize(4);

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +    }
// Verify no extraneous resources
        // Expect encounter, patient, practitioner, condition. <<??? don't know what you expect here.>>>
        assertThat(e).hasSize(4);

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +    }
// Verify no extraneous resources
        // Expect encounter, patient, practitioner, condition. <<??? don't know what you expect here.>>>
        assertThat(e).hasSize(4);

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +
Assert total resources:
      // Verify no extraneous resources
        // Expect encounter, patient, practitioner, condition. <<??? don't know what you expect here.>>>
        assertThat(e).hasSize(4);

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +
Assert total resources:
      // Verify no extraneous resources
        // Expect encounter, patient, practitioner, condition. <<??? don't know what you expect here.>>>
        assertThat(e).hasSize(4);

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +
Assert total resources:
      // Verify no extraneous resources
        // Expect encounter, patient, practitioner, condition. <<??? don't know what you expect here.>>>
        assertThat(e).hasSize(4);

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +    }
Assert total resources:
      // Verify no extraneous resources
        // Expect encounter, patient, practitioner, condition. <<??? don't know what you expect here.>>>
        assertThat(e).hasSize(4);

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +    }
Assert total resources:
      // Verify no extraneous resources
        // Expect encounter, patient, practitioner, condition. <<??? don't know what you expect here.>>>
        assertThat(e).hasSize(4);

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +
Assert total resources:
      // Verify no extraneous resources
        // Expect encounter, patient, practitioner, condition. <<??? don't know what you expect here.>>>
        assertThat(e).hasSize(4);

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "ORC|OP|1234|1234|0827|||||20210101000000||||||20210101000000||||||ORDERING FAC NAME||(9\n"
Simplify PV1, ORC.  Be explicit in RXO what fields are tested.  Simplify, remove unneeded fields.

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "ORC|NW|||||E|10^BID^D4^^^R||20180622230000||||||||||||||||||||I\n"
Simplify  ORC.  Be explicit in RXE what fields are tested.  Simplify, remove unneeded fields.

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "ORC|OP|1234|1234|0827|||||20210101000000||||||20210101000000||||||ORDERING FAC NAME||(9\n"
Simplify PV1, ORC.   Simplify, remove unneeded RXO fields.

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "ORC|NW|||||E|10^BID^D4^^^R||20180622230000||||||||||||||||||||I\n"
Simplify PV1, ORC. Simplify, remove unneeded RXO fields.

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "|1|PC^^measureofunits||2213^ORDERING^PROVIDER|||||day|||333^Take 1 tablet by mouth every 6 (six) hours.||7|PC|||Wheezing^Wheezing^PRN||||^DUONEB|20180622230000||||||7|7|7\n"; // RX
Split so RXE.23 and RXE.24 are at the start of the line (after a |).   We want people to not have to count fields.

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "ORC|OP|1234|1234|0827|||||20210101000000||||||20210101000000||||||ORDERING FAC NAME||(9\n"
Simplify PV1, ORC. Simplify, remove unneeded RXO fields.

2021-12-30 18:16 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "PID|||1234^^^^MR||DOE^JANE^|||F||||||||||||||||||||||\n"
Simplify PV1, ORC. Simplify, remove unneeded RXE fields.

2022-01-04 14:30 UTC, jgrant22 commented on src/main/java/io/github/linuxforhealth/hl7/data/SimpleDataValueResolver.java
> +        return  null;
added formatter settings and applied them to this file

2022-01-04 14:37 UTC, jgrant22 commented on src/main/resources/hl7/secondary/Dosage.yml
> +  condition: $rxo23  NOT_NULL
fixed

2022-01-04 14:37 UTC, jgrant22 commented on src/main/resources/hl7/secondary/DoseAndRate.yml
> +rateRatio_1:
added

2022-01-04 16:26 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "PV1||I|^^^Toronto^^5642 Hilly Av||||||770542^Doctor^Consulting^Jr||||||||||Visit_111|||||||||||||||||||||||||20210101000000\n"
simplified all test

2022-01-04 16:27 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "ORC|OP|1234|1234|0827|||||20210101000000||||||20210101000000||||||ORDERING FAC NAME||(9\n"
simplified all test

2022-01-04 16:27 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "RXO|00054418425^Dexamethasone 4 MG Oral Tablet^NDC^^^^^^dexamethasone (DECADRON) 4 MG TABS|||||"
simplified all test

2022-01-04 16:27 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "ORC|NW|||||E|10^BID^D4^^^R||20180622230000||||||||||||||||||||I\n"
simplified all test

2022-01-04 16:27 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "RXE|^Q24H&0600^^20210330144208^^ROU|DUONEB3INH^3 ML PLAS CONT : IPRATROPIUM-ALBUTEROL 0.5-2.5 (3) MG/3ML IN SOLN^ADS^^^^^^ipratropium-albuterol (DUONEB) nebulizer solution 3 mL|3||
simplified all test

2022-01-04 16:27 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "PV1||I|^^^Toronto^^5642 Hilly Av||||||770542^Doctor^Consulting^Jr||||||||||Visit_111|||||||||||||||||||||||||20210101000000\n"
simplified all test

2022-01-04 16:27 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "ORC|OP|1234|1234|0827|||||20210101000000||||||20210101000000||||||ORDERING FAC NAME||(9\n"
simplified all test

2022-01-04 16:30 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "ORC|NW|||||E|10^BID^D4^^^R||20180622230000||||||||||||||||||||I\n"
simplified all test

2022-01-04 16:30 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "ORC|OP|1234|1234|0827|||||20210101000000||||||20210101000000||||||ORDERING FAC NAME||(9\n"
simplified all test

2022-01-04 16:31 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "ORC|NW|||||E|10^BID^D4^^^R||20180622230000||||||||||||||||||||I\n"
simplified all test

2022-01-04 16:32 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "ORC|OP|1234|1234|0827|||||20210101000000||||||20210101000000||||||ORDERING FAC NAME||(9\n"
simplified all test

2022-01-04 17:57 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +
added

2022-01-04 17:58 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +    }
added

2022-01-04 17:58 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +    }
added

2022-01-04 17:58 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +
added

2022-01-04 17:58 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +
added

2022-01-04 17:58 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +
added

2022-01-04 17:58 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +    }
added

2022-01-04 17:58 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +    }
added

2022-01-04 17:58 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +    }
added

2022-01-04 17:59 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +    }
added

2022-01-04 18:59 UTC, cragun47 requested changes
Just a couple more changes of simplification.

2022-01-04 18:59 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +        // dosageInstruction.doseAndRate.doseRange.low(RXE.3)
Remove commented out code.

2022-01-04 18:59 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +        // dosageInstruction.doseAndRate.doseRange.high(RXE.4)
Remove commented code.

2022-01-04 18:59 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "|1|PC^^measureofunits|||||||day|||||7|PC|||Wheezing^Wheezing^PRN||||||||||7|7|7\n";
Simplify segment fields after RXE.5.  You're not testing them, and they are optional.

2022-01-04 18:59 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "|^Take 1 tablet by mouth every 6 (six) hours.|||G||4|tablet^tablet|0|222^JONES^JON^E.|||day||||6|PC^^http://unitsofmeasure.org||^DECADRON\n"
Simplify (make empty) segment fields after RXO.4.  You're not testing them, and they are optional.

2022-01-04 19:04 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +        // dosageInstruction.doseAndRate.doseRange.low(RXE.3)
this is a comment on whats being tested in the following assertions. In this case its DoseRange.Low...I will simplify

2022-01-04 19:04 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +        // dosageInstruction.doseAndRate.doseRange.high(RXE.4)
this is a comment on whats being tested in the following assertions. In this case its DoseRange.High...I will simplify

2022-01-04 19:40 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "|^Take 1 tablet by mouth every 6 (six) hours.|||G||4|tablet^tablet|0|222^JONES^JON^E.|||day||||6|PC^^http://unitsofmeasure.org||^DECADRON\n"
fixed

2022-01-04 19:40 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "|1|PC^^measureofunits|||||||day|||||7|PC|||Wheezing^Wheezing^PRN||||||||||7|7|7\n";
fixed

2022-01-04 19:52 UTC, cragun47 approved these changes
Thanks for making those changes.  Approved.

2022-01-04 19:53 UTC, merged