medicationCC and dispenseRequest.numberOfRepeatsAllowed + fix reason code precedence
LinuxForHealth/hl7v2-fhir-converter pull request #380
Opened 2022-01-04 21:26 UTC by jgrant22

from  705(the last of 705)

reason Code seemed to be working correctly but the precedence was slightly off so I fixed that

2022-01-04 22:27 UTC, cragun47 requested changes
Two changes requested.

2022-01-04 22:27 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                    + "|1|PC^^measureofunits||0||||||||||||||||||||||||||7|\n"; // RXE 10 & 11 & 13 are on this line
Thank you for simplifying data.

2022-01-04 22:27 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +        assertThat(disReq.getNumberOfRepeatsAllowed()).hasToString("0");
Thank you for reusing parses.

2022-01-04 22:27 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "RXE|||3||mL|47||||1|PC||||||||||||||||||||DUONEB3INH^3 ML PLAS CONT : IPRATROPIUM-ALBUTEROL 0.5-2.5 (3) MG/3ML IN SOLN^ADS^^^^^^ipratropium-albuterol (DUONEB) nebulizer solution 3
Which fields in RXE.31 are being checked?  There's a value in RXE.31.9 ??  Please remove the data or check it.

2022-01-04 22:27 UTC, cragun47 commented on src/main/resources/hl7/resource/MedicationRequest.yml
> +  specs: RXO.20 | RXE.27 | ORC.16
Missing RXA-19 and test.
>MedicationRequest.reasonCode precedence: RXO-20, RXE-27, RXA-19, ORC-16.

2022-01-04 22:36 UTC, jgrant22 commented on src/main/resources/hl7/resource/MedicationRequest.yml
> +  specs: RXO.20 | RXE.27 | ORC.16
None of the message types that we support create medication request from RXA segments

2022-01-04 22:40 UTC, cragun47 commented on src/main/resources/hl7/resource/MedicationRequest.yml
> +  specs: RXO.20 | RXE.27 | ORC.16
OK

2022-01-04 23:23 UTC, cragun47 approved these changes
Thanks for changes.

2022-01-05 14:31 UTC, merged

2022-01-05 14:46 UTC, LisaWellman commented on src/main/resources/hl7/resource/MedicationRequest.yml
> +  specs: RXO.20 | RXE.27 | ORC.16
Concerned that we were able to change this order and no testcases broke.  There should have been a testcase verifying the precedence of reasonCode.

2022-01-05 16:54 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "RXE|||3||mL|47||||1|PC||||||||||||||||||||DUONEB3INH^3 ML PLAS CONT : IPRATROPIUM-ALBUTEROL 0.5-2.5 (3) MG/3ML IN SOLN^ADS^^^^^^ipratropium-albuterol (DUONEB) nebulizer solution 3
sorry I thought I checked this off

2022-01-05 16:54 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7MedicationRequestFHIRConversionTest.java
> +                + "RXE|||3||mL|47||||1|PC||||||||||||||||||||DUONEB3INH^3 ML PLAS CONT : IPRATROPIUM-ALBUTEROL 0.5-2.5 (3) MG/3ML IN SOLN^ADS^^^^^^ipratropium-albuterol (DUONEB) nebulizer solution 3
this was taken care of