688 education
LinuxForHealth/hl7v2-fhir-converter pull request #381
Opened 2022-01-04 23:11 UTC by jgrant22

Immunization.education.presentationDate
Immunization.education.publicationDate
Immunization.education.documentType

2022-01-05 17:38 UTC, cragun47 requested changes
Please add tests and documentation as requested.

2022-01-05 17:38 UTC, cragun47 commented on src/main/resources/hl7/secondary/Education.yml
> +    obx31: String, OBX.3.1
Good varname update.

2022-01-05 17:38 UTC, cragun47 commented on src/main/resources/hl7/resource/Immunization.yml
> +         condition: $obx4 EQUALS $reference && $obx31 EQUALS 29768-9
I see the unit tests for checking for OBX.3.1 (equals various), but I don't see that we test when $reference (OBX.4) changes to a different value.  I know we're doing that to group the OBX's, but we need to have a) documentation in the work item about why and what we expect, b) a test which tests for the second grouping with the expected behavior and checking for data bleed (may need an additional test to look for data bleed),  c) some explanation in the code as to why, and good documentation in the tests about expectations.

2022-01-05 17:38 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
>                  + "RXA|0|1|20130531|20130531|48^HIB PRP-T^CVX|0.5|ML^^^||00^new immunization record^NIP001|^Sticker^Nurse|^^^RI2050||||33k2a|20131210|PMC^sanofi^MVX|00^Patient refusal^NIP002|||A\r"
Please simplify data to minimum used for testing.

2022-01-05 17:38 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        String hl7VUXmessageRep = "MSH|^~\\&|MYEHR2.5|RI88140101|KIDSNET_IFL|RIHEALTH|20130531||VXU^V04^VXU_V04|20130531RI881401010105|P|2.5.1|||NE|AL||||||RI543763\r"
Simplify data to that used for testing.

2022-01-05 17:38 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +                + "OBX|1|DTM|29768-9^VIS Publication Date^LN|1|19981216||||||F|||20130531|||VXC40^per imm^CDCPHINVS\r"
Need test that show what happens if OBX.4 changes  to a different value. Right now we have all the same OBX.4 value, and we're testing for that in the YML.   Test for different value, and also test for bleed/mixing issues (when OBX.3.1 is good, but the OBX.4 is changed.)

2022-01-05 17:38 UTC, cragun47 commented on src/main/resources/hl7/resource/Immunization.yml
> +         condition: $obx4 EQUALS $reference && $obx31 EQUALS 29768-9
@LisaWellman tag FYI

2022-01-05 18:09 UTC, LisaWellman requested changes

2022-01-05 18:09 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +                + "OBX|2|DT|69764-9^HIB Info Sheet^LN|1|19981216||||||F|||20130531|||VXC40^per imm^CDCPHINVS\r";
Segment added but no checks added or changed?

2022-01-05 18:09 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(immunization.getEducation().get(1).getDocumentType()).isEqualTo("unspecified");
Shouldn't this be PDF?

2022-01-05 18:09 UTC, LisaWellman commented on src/main/resources/hl7/resource/Immunization.yml
> +            notSpecified: "unspecified"
Please remind me if we discussed and I am forgetting - why is this hardcoded rather than OBX-5?
Why isn't it checking for OBX-3=69764-9 ?

documentType is not required, so we should not need a default

2022-01-05 18:13 UTC, LisaWellman commented on src/main/resources/hl7/resource/Immunization.yml
> +         condition: $obx4 EQUALS $reference && $obx31 EQUALS 29768-9
I am not sure why we are looking at OBX-4 at all, Jared if we discussed you may need to remind me.

2022-01-05 18:23 UTC, cragun47 commented on src/main/resources/hl7/resource/Immunization.yml
> +         condition: $obx4 EQUALS $reference && $obx31 EQUALS 29768-9
@LisaWellman   As I remember, there was something about OBX.4 creating a "set" of records that went together.  If there were  10 OBX's then those with the same OBX.4 were related. I can't find it.

Caristyx says: 
>This field is used to distinguish between multiple OBX segments with the same observation ID organized under one OBR. For example, a chest X-ray report might include three separate diagnostic impressions. The standard requires three OBX segments, one for each impression. By putting a 1 in the Sub-ID of the first of these OBX segments, 2 in the second, and 3 in the third, we can uniquely identify each OBX segment for editing or replacement.

2022-01-05 18:50 UTC, LisaWellman commented on src/main/resources/hl7/resource/Immunization.yml
> +         condition: $obx4 EQUALS $reference && $obx31 EQUALS 29768-9
I should also update the mappings spreadsheet if we are using OBX-4

2022-01-05 20:59 UTC, jgrant22 commented on src/main/resources/hl7/resource/Immunization.yml
> +            notSpecified: "unspecified"
correct I need to add the logic here but it was not passing validation without either reference or document type present.

2022-01-05 20:59 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +        assertThat(immunization.getEducation().get(1).getDocumentType()).isEqualTo("unspecified");
based off the comment below yes, I will fix this

2022-01-05 21:10 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7ImmunizationFHIRConversionTest.java
> +                + "OBX|2|DT|69764-9^HIB Info Sheet^LN|1|19981216||||||F|||20130531|||VXC40^per imm^CDCPHINVS\r";
I think this was by mistake I removed it

2022-01-05 23:26 UTC, LisaWellman commented on src/main/resources/hl7/resource/Immunization.yml
> +            notSpecified: "unspecified"
Please add a TODO if this is not resolved in this PR

2022-07-05 17:15 UTC, LisaWellman commented
I believe this was superseded by other PRs and this is no longer needed.

2022-07-05 17:15 UTC, closed without merging