enhance adt a03 test and update yml
LinuxForHealth/hl7v2-fhir-converter pull request #391
Opened 2022-01-11 18:51 UTC by jgrant22

Verify the message-level yml creates the correct resources
Create message-level unit tests

2022-01-11 19:56 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/ResourceUtils.java
> +        System.out.println(json);
Remove println

2022-01-11 20:11 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/ResourceUtils.java
> +        System.out.println(json);
thanks ! Did not mean to push this file up

2022-01-11 20:18 UTC, cragun47 requested changes
Required: new line at end of YML.
Responses to questions. (May need to add test for ROL)
Simplify data.

2022-01-11 20:18 UTC, cragun47 commented on src/main/resources/hl7/message/ADT_A03.yml
> +        - PV1
Add blank line at end of YML file.

2022-01-11 20:18 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +    void test_adta03_resources_present() throws IOException {
Name to camelCase

2022-01-11 20:18 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                + "PR1|1|ICD10|B45678|Fix break|20210322155008|A|75||V46|80|||32|1|D22|G45|1|G|P98|X|0|0\r"
Simplify PR1, because we are not testing contents.  PR1.1, 3, 5 are required.

2022-01-11 20:18 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                + "OBX|1|NM|111^TotalProtein||7.5|gm/dl|5.9-8.4||||F\r"
Simplify OBX, because we are not testing contents. OBX.2, 3 should be sufficient.

2022-01-11 20:18 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                + "AL1|1|DA|1605^acetaminophen^L|MO|Muscle Pain~hair loss\r"
Simplify AL1, because we are not testing contents. AL1.1,3 are required.

2022-01-11 20:18 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                + "PID|||1234^^^^MR||DOE^JANE^|||F||||||||||||||||||||||\r"
Simplify PID, because we are not testing contents. PID.2 is required.

2022-01-11 20:18 UTC, cragun47 commented on src/main/resources/hl7/message/ADT_A03.yml
> +      additionalSegments:
We're using ROL, but I don't see if it is being tested anywhere.

2022-01-11 20:23 UTC, lisadier requested changes

2022-01-11 20:23 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +    void test_adta03_resources_present() throws IOException {
Rather than just one test, create multiple tests, similar to what has been done for adt-a01 messages.  For example, create tests that cover a message with and without optional segments as well as tests that cover repeating segments and groups.
At first glance, I would expect tests such as:
test_adt_a03_mininum_segments
test_adt_a03_minimum_plus_PROCEDURE_group
test_adt_a03_minimum_plus_INSURANCE_group
test_adt_a03_full_with_no_groups
test_adt_a03_full_plus_multiple_PROCEDURE_and_INSURANCE_groups
As you dig into it you might find others are appropriate too, but this list is a starting point.  We don't have to cover every possible combination of optional and repeating segments or groups but we need reasonable coverage of the options.

2022-01-11 20:25 UTC, lisadier commented
I did not review the yml since Brian has taken a look at that.

2022-01-11 21:03 UTC, jgrant22 commented on src/main/resources/hl7/message/ADT_A03.yml
> +      additionalSegments:
mentioned in slack the ROL is not supported. https://ibm-watsonhealth.slack.com/archives/C01RXJ8Q2ET/p1641932435124800?thread_ts=1641929480.122600&cid=C01RXJ8Q2ET

2022-01-11 21:03 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                + "PID|||1234^^^^MR||DOE^JANE^|||F||||||||||||||||||||||\r"
done

2022-01-12 06:15 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +    void test_adta03_resources_present() throws IOException {
added tests

2022-01-12 06:16 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/segments/util/ResourceUtils.java
> +        System.out.println(json);
removed

2022-01-12 06:37 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +    void test_adta03_resources_present() throws IOException {
fixed

2022-01-12 06:38 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                + "OBX|1|NM|111^TotalProtein||7.5|gm/dl|5.9-8.4||||F\r"
fixed

2022-01-12 06:38 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                + "AL1|1|DA|1605^acetaminophen^L|MO|Muscle Pain~hair loss\r"
fixed

2022-01-12 06:38 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                + "PR1|1|ICD10|B45678|Fix break|20210322155008|A|75||V46|80|||32|1|D22|G45|1|G|P98|X|0|0\r"
fixed

2022-01-12 15:18 UTC, cragun47 commented on src/main/resources/hl7/message/ADT_A03.yml
> +        - PV1
Done.  Thank you.

2022-01-12 15:21 UTC, cragun47 approved these changes
Thank you for making the changes I requested.  I approve.

(@lisadier  may still have some requirements)

2022-01-12 18:03 UTC, lisadier requested changes
Jared, this is looking good, I had just a couple more comments.

2022-01-12 18:03 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +    void testAdtA03AllResourcesPresent() throws IOException {
Let's include groups in the name of this test since it covers multiple groups.  Also please remove 'resources' from the name since we are structuring these tests around the segments+groups in the message.  Proposed name: "testAdt03AllSegmentsAndMultipleGroups"

2022-01-12 18:03 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +    void testAdtA03AllResourcesNoGroupsPresent() throws IOException {
Use 'segments' rather than 'resources' in the function name: testAdtA03AllSegmentsNoGroups

2022-01-12 19:31 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +    void testAdtA03AllResourcesNoGroupsPresent() throws IOException {
switched

2022-01-12 19:32 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +    void testAdtA03AllResourcesPresent() throws IOException {
fixed

2022-01-12 19:32 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                + "IN1||||Large Blue Organization|456 Ultramarine Lane^^Faketown^CA^ZIP5\n";
added

2022-01-12 19:32 UTC, jgrant22 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +                + "PID|||1234^^^^MR\r"
fixed

2022-01-12 20:17 UTC, lisadier approved these changes
Looks good, thanks Jared!

2022-01-12 20:18 UTC, merged