Issue411 IN2.72 backup IN1.17;  tables 0063 & 0344
LinuxForHealth/hl7v2-fhir-converter pull request #415
Opened 2022-01-22 00:02 UTC by cragun47

Signed-off-by: Brian Cragun <cragun@us.ibm.com>

IN2.72 as backup relationship for IN1.17.
NOTE: special rules apply for interpreting the direction of the relationship as input and mapping to the direction of the relationship expected by the FHIR field.

Added detailed notes in v2ToFhirMapping.yml IMPORTANT NOTES ON RELATIONSHIP MAPPINGS

2022-01-23 14:55 UTC, LisaWellman requested changes
Some of the mappings are from a different terminology system, we either need to handle that or change the mappings.

I've been thinking about the values where there is more specificity in the source than the target.  It might be better to retain that information by not mapping, and then retaining the HL7 table in the system.  I will add to card 1129.

I think we can simplify the comments a bit, we can discuss if you'd like.

2022-01-23 14:55 UTC, LisaWellman commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +  09: U # 'Unknown' as input
'U' is a different coding system - http://terminology.hl7.org/CodeSystem/v2-0131 instead of http://terminology.hl7.org/CodeSystem/v3-RoleCode.  I don't think this will work in the code as it is assuming v3 role code

2022-01-23 14:55 UTC, LisaWellman commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +  10: O # Handicapped dependent input, Other output
Same for 'O', this is also http://terminology.hl7.org/CodeSystem/v2-0131 not v3 role code

2022-01-23 14:55 UTC, LisaWellman commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +  14: O # Niece/Nephew input, Other output
'O' is a different terminology system
'EXT' looks like a better mapping

2022-01-23 14:55 UTC, LisaWellman commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +  06: PRN  # Foster child input from Type 2, is Parent in Type 1.
This should be PRNFOST

2022-01-23 14:55 UTC, LisaWellman commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +# 08: no good match for Employee
Could us 'E' (Employer) but this is from http://terminology.hl7.org/CodeSystem/v2-0131

2022-01-23 14:55 UTC, LisaWellman commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +  05: PRN  # Step child input from Type 2, is Parent in Type 1.
As above, suggest simplifying the comments to:
`# Step child : Parent`

2022-01-23 14:55 UTC, LisaWellman commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +# Input codes from IN2.72 (TYPE 2) values from table 0344, need to be REVERSED for TYPE1 POLICYHOLDER_RELATIONSHIP code from V3RoleCode.
Once I get to here I find "type 1" and "type 2" unhelpful.  All I need to know here is that the values need to be reversed for this section.
I would remove any mentions of type1/2 from here on down.

2022-01-23 14:55 UTC, LisaWellman commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
>    UNK: U
I hadn't noticed this 'U' here, or the 'O' on line 439, those I think will be issues as mentioned above.
It would be nice to add comments on what these values mean like you did for the new mappings.

2022-01-23 14:55 UTC, LisaWellman commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +# Input codes from IN1.17 (TYPE1) table 0063 are REVERSED for TYPE2 SUBSCRIBER_RELATIONSHIP codes from SubscriberRelationship
Make these comment consistent with other sections.  Seems too detailed/confusing, all we need to know here is what we are mapping from/to and if we need to reverse.

2022-01-23 14:55 UTC, LisaWellman commented on src/main/resources/hl7/resource/Coverage.yml
> +    condition: $relatedRelationshipStr EQUALS SEL || $relatedRelationshipStr EQUALS 01
I think we still need the check for NOT_NULL, or explain why not.

2022-01-23 14:55 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7FinancialInsuranceTest.java
> +        assertThat(relatedPersons).hasSize(1); // From IN1.16 through IN1.19; IN1.43; INI.49
Correct comment to reference IN2.72 instead of IN1 fields

2022-01-23 14:55 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7FinancialInsuranceTest.java
> +                // IN2.72 to Coverage.relationship and RelatedPerson.relationship.  (Backup for IN1.17) Codes from table 0344
Add to comment here that 04=natural child

2022-01-23 14:55 UTC, LisaWellman commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7FinancialInsuranceTest.java
> +                // IN1.17 purposely empty to validate IN2.62 works as secondary
Correct comment: IN2.62 should be IN2.72

2022-01-24 15:19 UTC, cragun47 commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +# Mapping to V3 Role code (used for POLICYHOLDER_RELATIONSHIP)
Done.

2022-01-24 15:44 UTC, cragun47 commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +# This is the reverse of the relationships from V3RoleCode.  See IMPORTANT NOTES ON RELATIONSHIP MAPPINGS above.
done

2022-01-24 15:46 UTC, cragun47 commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +# Input codes from IN2.72 (TYPE 2) values from table 0344, are standard match for TYPE 2 SUBSCRIBER_RELATIONSHIP codes from SubscriberRelationship.
done.

2022-01-24 15:48 UTC, cragun47 commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +  06: PRN  # Foster child input from Type 2, is Parent in Type 1.
DONE

2022-01-24 15:49 UTC, cragun47 commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +  05: PRN  # Step child input from Type 2, is Parent in Type 1.
I like it.

2022-01-24 16:00 UTC, cragun47 commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +# Input codes from IN1.17 (TYPE1) table 0063 are REVERSED for TYPE2 SUBSCRIBER_RELATIONSHIP codes from SubscriberRelationship
I like at least knowing what the number code is, otherwise you must pull up the table.

2022-01-24 16:00 UTC, cragun47 commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +# Input codes from IN1.17 (TYPE1) table 0063 are REVERSED for TYPE2 SUBSCRIBER_RELATIONSHIP codes from SubscriberRelationship
@LisaWellman  review

2022-01-24 16:06 UTC, cragun47 commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +  03: PRN  # Natural child financial responsibility input from Type 2, is Parent in Type 1.
Done.  I like it.

2022-01-24 16:07 UTC, cragun47 commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +  09: U # 'Unknown' as input
Changed to 
`# 09: Unknown: no good match `

2022-01-24 16:08 UTC, cragun47 commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +  10: O # Handicapped dependent input, Other output
Changed to: `# 10: Handicapped dependent input: no good match `

2022-01-24 16:10 UTC, cragun47 commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +  14: O # Niece/Nephew input, Other output
Changed to:   `14: EXT # Niece/Nephew :  Extended`

2022-01-24 16:10 UTC, cragun47 commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +# 08: no good match for Employee
I think we should stay away from all Employer / Employee, unless you want to get into it.   @LisaWellman  ??

2022-01-24 16:16 UTC, cragun47 commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
>    UNK: U
Done.  Changed to `# UNK: Unknown : no good match`

2022-01-24 16:18 UTC, cragun47 commented on src/main/resources/hl7/resource/Coverage.yml
> +    condition: $relatedRelationshipStr EQUALS SEL || $relatedRelationshipStr EQUALS 01
Done.

2022-01-24 16:19 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7FinancialInsuranceTest.java
> +        assertThat(relatedPersons).hasSize(1); // From IN1.16 through IN1.19; IN1.43; INI.49
Done.  Good catch.

2022-01-24 16:21 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7FinancialInsuranceTest.java
> +                // IN1.17 purposely empty to validate IN2.62 works as secondary
Done

2022-01-24 16:22 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/segments/Hl7FinancialInsuranceTest.java
> +                // IN2.72 to Coverage.relationship and RelatedPerson.relationship.  (Backup for IN1.17) Codes from table 0344
Done

2022-01-24 17:39 UTC, LisaWellman approved these changes
Thanks Brian, the comments are much clearer.
Just a couple minor items, approving.

2022-01-24 17:39 UTC, LisaWellman commented on src/main/java/io/github/linuxforhealth/hl7/data/SimpleDataValueResolver.java
> +    // Relationships are coded, mapped, and recoded in two different DIRECTIONS:
I am confused by this comment, because it is combining both the HL7 and FHIR items, yet is talking about the relationship direction which is specific to a field.  When looking at this class/function, I don't think this is really important, it is just using the mappings so I would remove but if you think it is valuable here maybe you want something like this:
```
    // Relationships are coded, mapped, and recoded in two different DIRECTIONS:
    //  - Insured to Patient.  Example: Insured is parent of child patient.
    //        IN1.17 and RelatedPersion.relationship have this direction. 
    //  - Patient to Insured.  Example: Patient is child of insured parent. 
    //        IN2.61 and Coverage.relationship have this direction.
    // See detailed notes in v2ToFhirMapping.yml, maps V3RoleCode and SubscriberRelationship
```

Then before POLICYHOLDER_RELATIONSHIP
```
// Maps from IN1.17 and IN2.72 to http://terminology.hl7.org/CodeSystem/v3-RoleCode.  
// Used for Coverage.relationship.
```

And before SUBSCRIBER_RELATIONSHIP
```
// Maps from IN1.17 and IN2.72 to http://terminology.hl7.org/CodeSystem/subscriber-relationship .
// Used for RelatedPerson.relationship.
```

2022-01-24 17:39 UTC, LisaWellman commented on src/main/resources/hl7/codesystem/v2ToFhirMapping.yml
> +# Codes from IN1.17 (values from table 0063) must be REVERSED for Coverage.relationship
Put IN1.17 mappings first (before IN2.72)

2022-01-24 18:23 UTC, merged