Issue#463 support for addtl adt msgs and in1/in2
LinuxForHealth/hl7v2-fhir-converter pull request #464
Opened 2022-02-25 01:08 UTC by cragun47

This makes official support for ADT^A01, ^A03, ^A04, ^A08, ^A28, ^A31 messages -- segments MSH, EVN, PID, PD1, PV1, PV2, OBX, Al1, DG1, PR1, IN1, IN2.
Extend support for IN1/IN2 to these messages.

Tests extended in HL7ADTMessageTest and Hl7FinancialInsuranceTest for coverage.

2022-02-25 18:36 UTC, lisadier requested changes
Brian, the code is great. I noted a couple suggestions in the comments above. Thanks for going the extra mile to clean up some additional items along the way and making sure the documentation is good!

2022-02-25 18:36 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
>      void testAdtA01FullPlusMultipleProcedureGroup(String message) throws IOException {
Suggestion to include Insurance in the name of the test:  testAdtA01FullPlusMultipleProcedureGroupAndInsuranceGroup

2022-02-25 18:36 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +    void testAdtA28A31AllSegments(String message) throws IOException {
Let's keep the pattern where we have the message structure in the name of the test and mention the groups:   testAdtA05FullWithMultipleProceduresAndSingleInsurance

2022-02-25 18:36 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +    @ParameterizedTest
Will you add an additional test:
testAdtA05MinimumWithNoProceduresAndMultipleInsurance
I debated about suggesting other combinations but I think adding this one will give us sufficient coverage.  My thinking is that we need to cover a minimal message for this structure and we need to cover multiple insurance groups.  For efficiency, we can test those with one parameterized test.

2022-02-25 18:36 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +        assertThat(e).hasSize(7);
Thanks for updating all of these hasSize functions.

2022-02-25 18:36 UTC, lisadier commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +        assertThat(e).hasSize(4);
In the ADT_A03 tests, there is no test with an IN2 segment.  This test testAdtA03MinimumPlusInsuranceGroup, would be a good one to include an IN2 segment so we have some coverage of ADT_A03 with IN2.

2022-02-25 19:10 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
>      void testAdtA01FullPlusMultipleProcedureGroup(String message) throws IOException {
Done.  Named: testAdtA01FullPlusMultipleProcedureGroupAndInsurance. (because insurance really isn't a group, here.)

2022-02-25 19:13 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +    void testAdtA28A31AllSegments(String message) throws IOException {
Renamed to testAdtA28A31WithAllergiesMultipleProceduresAndSingleInsurance

2022-02-25 19:29 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +    @ParameterizedTest
done

2022-02-25 19:30 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +        assertThat(e).hasSize(7);
Yep

2022-02-25 19:32 UTC, cragun47 commented on src/test/java/io/github/linuxforhealth/hl7/message/HL7ADTMessageTest.java
> +        assertThat(e).hasSize(4);
done

2022-02-25 19:35 UTC, cragun47 commented
This is done.  Ready for rereview and approval.  @lisadier

2022-02-28 14:39 UTC, lisadier approved these changes
Looks great, thanks Brian for the updates!

2022-02-28 14:51 UTC, merged